
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.4'
version_full = 'e00d9fb150b575ffbdfb92c386fd476190ae1a78'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

