
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(src/python/etcd/BUILD:etcd_library)

from setuptools import setup

setup(**
{   'description': 'Full fledged etcd-client for python. Batteries included',
    'install_requires': ['requests>=2.2.1', 'grequests>=0.2.0'],
    'name': 'py-etcd',
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': ['etcd'],
    'version': '0.1.4'}
)
