
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.2'
version_full = 'a23efe3a1d07abed44d1f59cf2fadf031bb374ab'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

