
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.7'
version_full = 'fb1a72a416c17a5953daf87db16bb786bded792b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

