
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x1e\xfd\x9d4\xaeL`\x9d\x17r\xf7s-a\xa0\xbd'
    
_lr_action_items = {'$end':([1,4,5,6,12,16,17,19,22,24,],[0,-4,-2,-1,-6,-4,-3,-5,-8,-7,]),'NAME':([0,3,8,9,],[2,4,15,16,]),'ARROW':([2,],[3,]),'LPAREN':([4,15,16,],[7,20,7,]),'DOT':([4,16,],[8,8,]),'COMMA':([10,11,13,14,21,23,],[-12,-10,18,-11,-9,18,]),'RPAREN':([7,10,11,13,14,20,21,23,],[12,-12,-10,19,-11,22,-9,24,]),'NUMBER':([7,18,20,],[10,10,10,]),'EQUALS':([4,],[9,]),'LITERAL':([7,18,20,],[14,14,14,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'scope':([0,],[1,]),'optional_argument':([7,18,20,],[11,21,11,]),'expression':([3,9,],[5,17,]),'parameters':([7,20,],[13,23,]),'statement':([3,],[6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> scope","S'",1,None,None,None),
  ('scope -> NAME ARROW statement','scope',3,'p_scope','/usr/lib/python3.3/site-packages/iac/parser.py',110),
  ('statement -> expression','statement',1,'p_statement_expr','/usr/lib/python3.3/site-packages/iac/parser.py',114),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','/usr/lib/python3.3/site-packages/iac/parser.py',117),
  ('expression -> NAME','expression',1,'p_expression_name','/usr/lib/python3.3/site-packages/iac/parser.py',121),
  ('expression -> NAME LPAREN parameters RPAREN','expression',4,'p_expression_function','/usr/lib/python3.3/site-packages/iac/parser.py',126),
  ('expression -> NAME LPAREN RPAREN','expression',3,'p_expression_function','/usr/lib/python3.3/site-packages/iac/parser.py',127),
  ('expression -> NAME DOT NAME LPAREN parameters RPAREN','expression',6,'p_expression_function','/usr/lib/python3.3/site-packages/iac/parser.py',128),
  ('expression -> NAME DOT NAME LPAREN RPAREN','expression',5,'p_expression_function','/usr/lib/python3.3/site-packages/iac/parser.py',129),
  ('parameters -> parameters COMMA optional_argument','parameters',3,'p_parameters','/usr/lib/python3.3/site-packages/iac/parser.py',148),
  ('parameters -> optional_argument','parameters',1,'p_parameters','/usr/lib/python3.3/site-packages/iac/parser.py',149),
  ('optional_argument -> LITERAL','optional_argument',1,'p_optional_argument_literal','/usr/lib/python3.3/site-packages/iac/parser.py',158),
  ('optional_argument -> NUMBER','optional_argument',1,'p_optional_argument_number','/usr/lib/python3.3/site-packages/iac/parser.py',162),
]
