# Generated by setup.py do not modify
import os
import sys
prefix = 'sys.prefix'
if hasattr(sys, 'frozen'):
    pos = __file__.find('library.zip')
    prefix = os.path.dirname(__file__[:pos-1])
elif not os.path.exists(prefix):
    prefix = sys.prefix
revision = 0
resources = {}
resources['locale'] = os.path.join(prefix, "share", "stoq", "..", "locale")
resources['plugin'] = os.path.join(prefix, "share", "stoq", "plugins")
global_resources = {}
global_resources['uixml'] = os.path.join(prefix, "share", "stoq", "uixml")
global_resources['pixmaps'] = os.path.join(prefix, "share", "stoq", "pixmaps")
global_resources['docs'] = os.path.join(prefix, "share", "stoq", "..", "doc", "stoq")
global_resources['misc'] = os.path.join(prefix, "share", "stoq", "misc")
global_resources['glade'] = os.path.join(prefix, "share", "stoq", "glade")
global_resources['html'] = os.path.join(prefix, "share", "stoq", "html")
global_resources['template'] = os.path.join(prefix, "share", "stoq", "template")
global_resources['sql'] = os.path.join(prefix, "share", "stoq", "sql")
global_resources['csv'] = os.path.join(prefix, "share", "stoq", "csv")
