#ifndef NT2_TOOLBOX_OPERATOR_FUNCTIONS_HPP_INCLUDED
#define NT2_TOOLBOX_OPERATOR_FUNCTIONS_HPP_INCLUDED

#include <nt2/toolbox/operator/include/functions/assign.hpp>
#include <nt2/toolbox/operator/include/functions/bitwise_and.hpp>
#include <nt2/toolbox/operator/include/functions/bitwise_cast.hpp>
#include <nt2/toolbox/operator/include/functions/bitwise_or.hpp>
#include <nt2/toolbox/operator/include/functions/bitwise_xor.hpp>
#include <nt2/toolbox/operator/include/functions/comma.hpp>
#include <nt2/toolbox/operator/include/functions/complement.hpp>
#include <nt2/toolbox/operator/include/functions/complexify.hpp>
#include <nt2/toolbox/operator/include/functions/divides.hpp>
#include <nt2/toolbox/operator/include/functions/eq.hpp>
#include <nt2/toolbox/operator/include/functions/extract.hpp>
#include <nt2/toolbox/operator/include/functions/ge.hpp>
#include <nt2/toolbox/operator/include/functions/gt.hpp>
#include <nt2/toolbox/operator/include/functions/if_else.hpp>
#include <nt2/toolbox/operator/include/functions/insert.hpp>
#include <nt2/toolbox/operator/include/functions/is_equal.hpp>
#include <nt2/toolbox/operator/include/functions/is_greater.hpp>
#include <nt2/toolbox/operator/include/functions/is_greater_equal.hpp>
#include <nt2/toolbox/operator/include/functions/is_less.hpp>
#include <nt2/toolbox/operator/include/functions/is_less_equal.hpp>
#include <nt2/toolbox/operator/include/functions/is_not_equal.hpp>
#include <nt2/toolbox/operator/include/functions/le.hpp>
#include <nt2/toolbox/operator/include/functions/load.hpp>
#include <nt2/toolbox/operator/include/functions/logical_and.hpp>
#include <nt2/toolbox/operator/include/functions/logical_not.hpp>
#include <nt2/toolbox/operator/include/functions/logical_or.hpp>
#include <nt2/toolbox/operator/include/functions/lt.hpp>
#include <nt2/toolbox/operator/include/functions/make.hpp>
#include <nt2/toolbox/operator/include/functions/map.hpp>
#include <nt2/toolbox/operator/include/functions/minus.hpp>
#include <nt2/toolbox/operator/include/functions/modulo.hpp>
#include <nt2/toolbox/operator/include/functions/multiplies.hpp>
#include <nt2/toolbox/operator/include/functions/ne.hpp>
#include <nt2/toolbox/operator/include/functions/plus.hpp>
#include <nt2/toolbox/operator/include/functions/shift_left.hpp>
#include <nt2/toolbox/operator/include/functions/shift_right.hpp>
#include <nt2/toolbox/operator/include/functions/splat.hpp>
#include <nt2/toolbox/operator/include/functions/store.hpp>
#include <nt2/toolbox/operator/include/functions/stream.hpp>
#include <nt2/toolbox/operator/include/functions/times.hpp>
#include <nt2/toolbox/operator/include/functions/uminus.hpp>
#include <nt2/toolbox/operator/include/functions/unaligned_load.hpp>
#include <nt2/toolbox/operator/include/functions/unaligned_store.hpp>
#include <nt2/toolbox/operator/include/functions/unary_minus.hpp>
#include <nt2/toolbox/operator/include/functions/unary_plus.hpp>
#include <nt2/toolbox/operator/include/functions/uplus.hpp>

#endif
