__version__ = "0.2.18"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.2.18)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'e643695b568788ee4804682a250441cb733ddacd'
__git_head_subject__ = 'fix indentation'
__git_head_message__ = ''
__git_dirty_diff__ = ''