# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/kRPCSpaceCenter/Schema/Resources.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/kRPCSpaceCenter/Schema/Resources.proto',
  package='Resources',
  serialized_pb='\n*src/kRPCSpaceCenter/Schema/Resources.proto\x12\tResources\"\x16\n\x05Names\x12\r\n\x05names\x18\x01 \x03(\t')




_NAMES = _descriptor.Descriptor(
  name='Names',
  full_name='Resources.Names',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='Resources.Names.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['Names'] = _NAMES

class Names(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NAMES

  # @@protoc_insertion_point(class_scope:Resources.Names)


# @@protoc_insertion_point(module_scope)
