
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.2'
version_full = '4d869b8754f663787cffb433a1b50857a7ed5009'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

