
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.6'
version_full = '2eeafadd108fcec0a2df6d5cb4af56d00d7fc5e3'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

