__version__ = "0.5.7"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "yalon@infinidat.com"
__git_branch__ = '(detached from v0.5.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'c6965826d9d65397976daa72a63b13bb717dc5cb'
__git_head_subject__ = 'HOSTDEV-1719 setting HAVE_LIBSSL, HAVE_LIBCRYPTO and reordered the -lcrypto and -lssl so _ssl module will build correctly'
__git_head_message__ = ''
__git_dirty_diff__ = ''