#ifndef NT2_TOOLBOX_LINALG_INCLUDE_FUNCTIONS_OPTIONS_HPP_INCLUDED
#define NT2_TOOLBOX_LINALG_INCLUDE_FUNCTIONS_OPTIONS_HPP_INCLUDED

#include <nt2/toolbox/linalg/functions/solvers/options.hpp>

#endif
