__version__ = "0.1.22"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.22)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7b6dedf343069f62cd3f3eec18cf1a92255e6910'
__git_head_subject__ = 'Finished release v0.1.22.'
__git_head_message__ = '* release/v0.1.22:\n  TRIVIAL fixing stripping\n  TRIVIAL fixing stripping'
__git_dirty_diff__ = ''