EXTRA_COLUMNS = {
    'CORE_PROCESSED': [
        {'field': 'daystoevent', 'type': 'bigint'},
        {'field': 'visitlink', 'type': 'bigint'},
        {'field': 'hospstco', 'type': 'integer'},
        {'field': 'hospid', 'type': 'integer'},
        {'field': 'dshospid', 'type': 'character varying'},
        {'field': 'ahaid', 'type': 'character varying'},
        {'field': 'cm_wghtloss', 'type': 'integer'},
        {'field': 'cm_valve', 'type': 'integer'},
        {'field': 'cm_ulcer', 'type': 'integer'},
        {'field': 'cm_tumor', 'type': 'integer'},
        {'field': 'cm_renlfail', 'type': 'integer'},
        {'field': 'cm_pulmcirc', 'type': 'integer'},
        {'field': 'cm_psych', 'type': 'integer'},
        {'field': 'cm_perivasc', 'type': 'integer'},
        {'field': 'cm_para', 'type': 'integer'},
        {'field': 'cm_obese', 'type': 'integer'},
        {'field': 'cm_neuro', 'type': 'integer'},
        {'field': 'cm_mets', 'type': 'integer'},
        {'field': 'cm_lytes', 'type': 'integer'},
        {'field': 'cm_lymph', 'type': 'integer'},
        {'field': 'cm_liver', 'type': 'integer'},
        {'field': 'cm_hypothy', 'type': 'integer'},
        {'field': 'cm_htn_c', 'type': 'integer'},
        {'field': 'cm_drug', 'type': 'integer'},
        {'field': 'cm_dmcx', 'type': 'integer'},
        {'field': 'cm_dm', 'type': 'integer'},
        {'field': 'cm_depress', 'type': 'integer'},
        {'field': 'cm_coag', 'type': 'integer'},
        {'field': 'cm_chrnlung', 'type': 'integer'},
        {'field': 'cm_chf', 'type': 'integer'},
        {'field': 'cm_bldloss', 'type': 'integer'},
        {'field': 'cm_arth', 'type': 'integer'},
        {'field': 'cm_anemdef', 'type': 'integer'},
        {'field': 'cm_alcohol', 'type': 'integer'},
        {'field': 'cm_aids', 'type': 'integer'},
        {'field': 'prmccs6', 'type': 'character varying'},
        {'field': 'prmccs5', 'type': 'character varying'},
        {'field': 'prmccs4', 'type': 'character varying'},
        {'field': 'prmccs3', 'type': 'character varying'},
        {'field': 'prmccs2', 'type': 'character varying'},
        {'field': 'prmccs1', 'type': 'character varying'},
        {'field': 'pclass6', 'type': 'integer'},
        {'field': 'pclass5', 'type': 'integer'},
        {'field': 'pclass4', 'type': 'integer'},
        {'field': 'pclass3', 'type': 'integer'},
        {'field': 'pclass2', 'type': 'integer'},
        {'field': 'pclass1', 'type': 'integer'},
        {'field': 'e_mccs6', 'type': 'character varying'},
        {'field': 'e_mccs5', 'type': 'character varying'},
        {'field': 'e_mccs4', 'type': 'character varying'},
        {'field': 'e_mccs3', 'type': 'character varying'},
        {'field': 'e_mccs2', 'type': 'character varying'},
        {'field': 'e_mccs1', 'type': 'character varying'},
        {'field': 'dxmccs9', 'type': 'character varying'},
        {'field': 'dxmccs8', 'type': 'character varying'},
        {'field': 'dxmccs7', 'type': 'character varying'},
        {'field': 'dxmccs6', 'type': 'character varying'},
        {'field': 'dxmccs5', 'type': 'character varying'},
        {'field': 'dxmccs4', 'type': 'character varying'},
        {'field': 'dxmccs3', 'type': 'character varying'},
        {'field': 'dxmccs2', 'type': 'character varying'},
        {'field': 'dxmccs1', 'type': 'character varying'},
        {'field': 'chronb9', 'type': 'integer'},
        {'field': 'chronb8', 'type': 'integer'},
        {'field': 'chronb7', 'type': 'integer'},
        {'field': 'chronb6', 'type': 'integer'},
        {'field': 'chronb5', 'type': 'integer'},
        {'field': 'chronb4', 'type': 'integer'},
        {'field': 'chronb3', 'type': 'integer'},
        {'field': 'chronb2', 'type': 'integer'},
        {'field': 'chronb1', 'type': 'integer'},
        {'field': 'chron9', 'type': 'integer'},
        {'field': 'chron8', 'type': 'integer'},
        {'field': 'chron7', 'type': 'integer'},
        {'field': 'chron6', 'type': 'integer'},
        {'field': 'chron5', 'type': 'integer'},
        {'field': 'chron4', 'type': 'integer'},
        {'field': 'chron3', 'type': 'integer'},
        {'field': 'chron2', 'type': 'integer'},
        {'field': 'chron1', 'type': 'integer'},
        {'field': 'u_icu', 'type': 'integer'},
        {'field': 'u_ccu', 'type': 'integer'},
        {'field': 'u_newbn2l', 'type': 'integer'},
        {'field': 'u_newbn3l', 'type': 'integer'},
        {'field': 'u_newbn4l', 'type': 'integer'},
        {'field': 'u_cath', 'type': 'integer'},
        {'field': 'u_stress', 'type': 'integer'},
        {'field': 'u_echo', 'type': 'integer'},
        {'field': 'u_ekg', 'type': 'integer'},
        {'field': 'u_ctscan', 'type': 'integer'},
        {'field': 'u_chestxray', 'type': 'integer'},
        {'field': 'u_ultrasound', 'type': 'integer'},
        {'field': 'u_eeg', 'type': 'integer'},
        {'field': 'u_nucmed', 'type': 'integer'},
        {'field': 'u_mrt', 'type': 'integer'},
        {'field': 'u_pacemaker', 'type': 'integer'},
        {'field': 'u_othimplants', 'type': 'integer'},
        {'field': 'u_lithotripsy', 'type': 'integer'},
        {'field': 'u_occtherapy', 'type': 'integer'},
        {'field': 'u_phytherapy', 'type': 'integer'},
        {'field': 'u_radtherapy', 'type': 'integer'},
        {'field': 'u_resptherapy', 'type': 'integer'},
        {'field': 'u_speechtherapy', 'type': 'integer'},
        {'field': 'u_blood', 'type': 'integer'},
        {'field': 'u_dialysis', 'type': 'integer'},
        {'field': 'u_epo', 'type': 'integer'},
        {'field': 'u_mhsa', 'type': 'integer'},
        {'field': 'u_ed', 'type': 'integer'},
        {'field': 'u_observation', 'type': 'integer'},
        {'field': 'u_organacq', 'type': 'integer'}
    ]
}