fishes = {
    'Rockfish': [
        'unknown rockfish',
        'unknown Sebastomus',
        'aurora rockfish',
        'bank rockfish',
        'blackgill',
        'black rockfish',
        'blackgill rockfish',
        'bocaccio',
        'brown rockfish',
        'canary rockfish',
        'chilipepper',
        'copper rockfish',
        'cowcod rockfish',
        'darkblotched rockfish',
        'flag rockfish',
        'greenblotched rockfish',
        'greenspotted rockfish',
        'greenstriped rockfish',
        'halfbanded rockfish',
        'honeycomb rockfish',
        'juvenile rockfish',
        'longspine thornyhead',
        'Pacific ocean perch',
        'pink rockfish',
        'pinkrose rockfish',
        'pygmy/Puget Sound rockfish',
        'quillback rockfish',
        'redbanded rockfish',
        'redstripe rockfish',
        'rosethorn rockfish',
        'rosy rockfish',
        'Sebastomus',
        'sharpchin rockfish',
        'shortbelly rockfish',
        'shortspine thornyhead',
        'splitnose rockfish',
        'splitnose/aurora',
        'squarespot rockfish',
        'starry rockfish',
        'stripetail rockfish',
        'swordspine rockfish',
        'thornyhead unident',
        'tiger rockfish',
        'vermillion rockfish',
        'widow rockfish',
        'yelloweye rockfish',
        'yellowtail rockfish',],
    'Flatfish': [
        'unknown flatfish',
        'bigmouth sole',
        'butter sole',
        'curlfin sole',
        'deepsea sole',
        'Dover sole',
        'English sole',
        'Pacific halibut',
        'Pacific sanddab',
        'petrale sole',
        'rex sole',
        'sand sole',
        'slender sole',
        'southern rock sole',
        'speckled sanddab',
    ],
    'Skates': [
        'unknown skate',
        'big skate',
        'California skate',
        'longnose skate',
        'starry skate',
    ],
    'Roundfish': [
        'unknown roundfish',
        'unknown sculpin',
        'unknown ronquil',
        'unknown poacher',
        'unknown eelpout',
        'unknown snailfish',
        'bigfin eelpout',
        'blackbelly eelpout',
        'cuskeel',
        'eelpout unident',
        'giant grenadier',
        'hagfish',
        'kelp greenling',
        'lingcod',
        'Pacific grenadier',
        'Pacific hake',
        'poacher/cottid',
        'sablefish',
        'slickheads',
        'spotted ratfish',
        'sturgeon poacher',
        'threadfin sculpin',
    ],
    'Invertebrates': [
        'unknown invertebrate',
        'unknown anemone',
        'unknown sponge',
        'unknown sea pen',
        'unknown gorgonian',
        'unknown coral',
        'unknown black coral',
        'unknown crab',
        'unknown cup coral',
        'unknown octopod',
        'Allocentrotus fragilis',
        'Anthomastus ritteri',
        'Anthomastus spp.',
        'barrel sponge',
        'black corals',
        'box crab',
        'brachiopod',
        'brittlestar unident',
        'Ceramaster patagonicus',
        'Crossaster papposus',
        'Dungeness crab',
        'Florometra serratissima',
        'foliose sponge',
        'galatheid crab',
        'Gorgonacephalus eucnemis',
        'gorgonian unident',
        'Henricia spp.',
        'hydrocoral unident',
        'Luidia foliolata',
        'Majidae',
        'Metridium farcimen',
        'Paralithodes spp.',
        'Parastichopus spp.',
        'Ptilosarcus gurneyi',
        'Poraniopsis inflata',
        'Rathbunaster californicus',
        'sea pen unident',
        'scleractinian coral unident',
        'shelf sponge',
        'Umbellula spp.',
        'vase sponge',
    ]
}

fish_codes = {
    'Rockfish': 'RO',
    'Flatfish': 'FL',
    'Skates': 'SK',
    'Roundfish': 'RN',
    'Invertebrates': 'IN',
}

substrate_types = ['unknown', 'R', 'B', 'C', 'P', 'S', 'M']