
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2'
version_full = 'c476b63af8c1d2f8ee2e609304ebc9d88386bc8e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

