#ifndef NT2_TOOLBOX_TRIGONOMETRIC_INCLUDE_FUNCTIONS_SCALAR_FAST_SINCOSD_HPP_INCLUDED
#define NT2_TOOLBOX_TRIGONOMETRIC_INCLUDE_FUNCTIONS_SCALAR_FAST_SINCOSD_HPP_INCLUDED

#include <nt2/toolbox/trigonometric/functions/fast_sincosd.hpp>
#include <nt2/toolbox/trigonometric/functions/scalar/fast_sincosd.hpp>

#endif
