__version__ = "0.1.4"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'e426e0825b2bca4a4a613b6d562e787c13aa40af'
__git_head_subject__ = 'HOSTDEV-1730 adding try/except around state(filepath)'
__git_head_message__ = ''
__git_dirty_diff__ = ''