
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.6'
version_full = 'f3036c6ee842296e8b2423be3f2cf3eb27373d44'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

