
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.13.3'
version_full = '0e7e6b97e0e49c2c70d1e6a3d96e00d2517dd4ce'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

