// File: bug_boolconst.v
// Generated by MyHDL 0.8.1
// Date: Sun Aug 24 16:31:04 2014


`timescale 1ns/10ps

module bug_boolconst (
    sigin,
    sigout
);


input sigin;
output sigout;
reg sigout;






always @(sigin) begin: BUG_BOOLCONST_OUTPUT
    sigout = 0;
    if (0) begin
        sigout = sigin;
    end
    if (0) begin
        sigout = sigin;
    end
    if ((!0)) begin
        sigout = sigin;
    end
    if ((!0)) begin
        sigout = sigin;
    end
    if (1) begin
        sigout = sigin;
    end
    if (1) begin
        sigout = sigin;
    end
    if ((!1)) begin
        sigout = sigin;
    end
    if ((!1)) begin
        sigout = sigin;
    end
end

endmodule
