// File: bug_1835792.v
// Generated by MyHDL 0.8.1
// Date: Sun Aug 24 16:31:00 2014


`timescale 1ns/10ps

module bug_1835792 (

);
// Semicolon conversion
// 
//     







initial begin: BUG_1835792_LOGIC
    reg signed [7-1:0] v;
    v = 0;
    # 10;
    $write("%0d", -15);
    $write("\n");
    $write("%0d", 45);
    $write("\n");
end

endmodule
