-- File: dut.vhd
-- Generated by MyHDL 0.8.1
-- Date: Sun Aug 24 16:31:09 2014


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_081.all;

entity dut is
end entity dut;


architecture MyHDL of dut is





signal count: unsigned(6 downto 0);

begin




DUT_SEQ: process is
    variable L: line;
begin
    count <= to_unsigned(50, 7);
    for i in 0 to 300-1 loop
        wait for 10 ns;
        write(L, to_integer(count));
        writeline(output, L);
        if ((signed(resize(count, 8)) - 1) < 0) then
            count <= to_unsigned(97, 7);
        else
            count <= (count - 1);
        end if;
    end loop;
    wait;
end process DUT_SEQ;

end architecture MyHDL;
