-- File: module.vhd
-- Generated by MyHDL 0.8.1
-- Date: Sun Aug 24 16:31:09 2014


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_081.all;

entity module is
    port (
        sigin: in unsigned(1 downto 0);
        sigout: out unsigned(1 downto 0)
    );
end entity module;


architecture MyHDL of module is






begin




MODULE_OUTPUT: process (sigin) is
begin
    sigout <= sigin(2-1 downto 0);
end process MODULE_OUTPUT;

end architecture MyHDL;
