
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.11.0'
version_full = 'f973c52c96e9c3c626db7881770f24305dd651f2'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

