from .processor_and_frequence_scaling import ProcessorAndFrequenceScaling
from .battery_charge_thresholds import BatteryChargeThresholds
from .system_start_and_shutdown import SystemStartAndShutdown
from .runtime_power_management import RuntimePowerManagement
from .wireless_radio_switch import WirelessRadioSwitch
from .disks_and_controllers import DisksAndControllers
from .drive_slot_ultrabay import DriveSlotUltrabay
from .pci_express_bus import PciExpressBus
from .graphics_cards import GraphicsCards
from .undervolting import Undervolting
from .file_system import FileSystem
from .networking import Networking
from .category import Category
from .kernel import Kernel
from .audio import Audio
from .usb import Usb
