
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.9.12'
version_full = '2f1e66f3d09ae9a9a0d33aeeb0b56712659fef76'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

