
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.10.0'
version_full = '3b435126bd68dd606876058c6958d46945ed99d5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

