
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6'
version_full = '72a29804783f0a73fdb40a5244a8c0f3c0026f90'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

