#ifndef NT2_TOOLBOX_TRIGONOMETRIC_FUNCTIONS_HPP_INCLUDED
#define NT2_TOOLBOX_TRIGONOMETRIC_FUNCTIONS_HPP_INCLUDED

#include <nt2/toolbox/trigonometric/include/functions/acos.hpp>
#include <nt2/toolbox/trigonometric/include/functions/acosd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/acospi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/acot.hpp>
#include <nt2/toolbox/trigonometric/include/functions/acotd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/acsc.hpp>
#include <nt2/toolbox/trigonometric/include/functions/acscd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/asec.hpp>
#include <nt2/toolbox/trigonometric/include/functions/asecd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/asin.hpp>
#include <nt2/toolbox/trigonometric/include/functions/asind.hpp>
#include <nt2/toolbox/trigonometric/include/functions/asinpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/atan.hpp>
#include <nt2/toolbox/trigonometric/include/functions/atan2.hpp>
#include <nt2/toolbox/trigonometric/include/functions/atand.hpp>
#include <nt2/toolbox/trigonometric/include/functions/atanpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cos.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cosd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cosecant.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cosine.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cospi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cot.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cotangent.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cotd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cotpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/csc.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cscd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/cscpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_cos.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_cosd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_cospi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_cot.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_cotd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_cotpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_sin.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_sincos.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_sincosd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_sincospi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_sind.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_sinpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_tan.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_tand.hpp>
#include <nt2/toolbox/trigonometric/include/functions/fast_tanpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/indeg.hpp>
#include <nt2/toolbox/trigonometric/include/functions/inrad.hpp>
#include <nt2/toolbox/trigonometric/include/functions/nbd_atan2.hpp>
#include <nt2/toolbox/trigonometric/include/functions/proper_tanpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/rem_2pi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/rem_pio2.hpp>
#include <nt2/toolbox/trigonometric/include/functions/rem_pio2_cephes.hpp>
#include <nt2/toolbox/trigonometric/include/functions/rem_pio2_medium.hpp>
#include <nt2/toolbox/trigonometric/include/functions/rem_pio2_straight.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sec.hpp>
#include <nt2/toolbox/trigonometric/include/functions/secant.hpp>
#include <nt2/toolbox/trigonometric/include/functions/secd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/secpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sin.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sinc.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sincos.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sincosd.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sincospi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sind.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sine.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sinecosine.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sinpi.hpp>
#include <nt2/toolbox/trigonometric/include/functions/sinpic.hpp>
#include <nt2/toolbox/trigonometric/include/functions/tan.hpp>
#include <nt2/toolbox/trigonometric/include/functions/tand.hpp>
#include <nt2/toolbox/trigonometric/include/functions/tangent.hpp>
#include <nt2/toolbox/trigonometric/include/functions/tanpi.hpp>

#endif
