__version__ = "0.0.5"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "yalon@infinidat.com"
__git_branch__ = '(detached from v0.0.5)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '1d8bcf623a9e57e7d0cb2a2455b57e907c2b9ca4'
__git_head_subject__ = 'changed upstart script to start after rc is done so we wont get garbage on screen'
__git_head_message__ = ''
__git_dirty_diff__ = ''