
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.13.4'
version_full = 'a8cf27d989647b96bbbe4d4b536b3195fc6de0e3'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

