
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.13'
version_full = '7a950be9298f381c4bf4901e383b8c3609197ff5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

