# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res\ui\widgets\location_config.ui'
#
# Created: Wed May 07 22:41:49 2014
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LocationConfigDialog(object):
    def setupUi(self, LocationConfigDialog):
        LocationConfigDialog.setObjectName(_fromUtf8("LocationConfigDialog"))
        LocationConfigDialog.resize(310, 145)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LocationConfigDialog.sizePolicy().hasHeightForWidth())
        LocationConfigDialog.setSizePolicy(sizePolicy)
        LocationConfigDialog.setMinimumSize(QtCore.QSize(310, 145))
        LocationConfigDialog.setMaximumSize(QtCore.QSize(310, 145))
        self.formLayout = QtGui.QFormLayout(LocationConfigDialog)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loc_label = QtGui.QLabel(LocationConfigDialog)
        self.loc_label.setObjectName(_fromUtf8("loc_label"))
        self.horizontalLayout.addWidget(self.loc_label)
        self.loc_edit = QtGui.QLineEdit(LocationConfigDialog)
        self.loc_edit.setObjectName(_fromUtf8("loc_edit"))
        self.horizontalLayout.addWidget(self.loc_edit)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lat_label = QtGui.QLabel(LocationConfigDialog)
        self.lat_label.setObjectName(_fromUtf8("lat_label"))
        self.horizontalLayout_2.addWidget(self.lat_label)
        self.lat_deg_edit = QtGui.QLineEdit(LocationConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_deg_edit.sizePolicy().hasHeightForWidth())
        self.lat_deg_edit.setSizePolicy(sizePolicy)
        self.lat_deg_edit.setMinimumSize(QtCore.QSize(32, 0))
        self.lat_deg_edit.setMaximumSize(QtCore.QSize(32, 16777215))
        self.lat_deg_edit.setMaxLength(2)
        self.lat_deg_edit.setObjectName(_fromUtf8("lat_deg_edit"))
        self.horizontalLayout_2.addWidget(self.lat_deg_edit)
        self.lat_deg_label = QtGui.QLabel(LocationConfigDialog)
        self.lat_deg_label.setTextFormat(QtCore.Qt.PlainText)
        self.lat_deg_label.setObjectName(_fromUtf8("lat_deg_label"))
        self.horizontalLayout_2.addWidget(self.lat_deg_label)
        self.lat_min_edit = QtGui.QLineEdit(LocationConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_min_edit.sizePolicy().hasHeightForWidth())
        self.lat_min_edit.setSizePolicy(sizePolicy)
        self.lat_min_edit.setMinimumSize(QtCore.QSize(32, 0))
        self.lat_min_edit.setMaximumSize(QtCore.QSize(32, 16777215))
        self.lat_min_edit.setMaxLength(2)
        self.lat_min_edit.setObjectName(_fromUtf8("lat_min_edit"))
        self.horizontalLayout_2.addWidget(self.lat_min_edit)
        self.lat_min_label = QtGui.QLabel(LocationConfigDialog)
        self.lat_min_label.setObjectName(_fromUtf8("lat_min_label"))
        self.horizontalLayout_2.addWidget(self.lat_min_label)
        self.lat_sec_edit = QtGui.QLineEdit(LocationConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_sec_edit.sizePolicy().hasHeightForWidth())
        self.lat_sec_edit.setSizePolicy(sizePolicy)
        self.lat_sec_edit.setMinimumSize(QtCore.QSize(32, 0))
        self.lat_sec_edit.setMaximumSize(QtCore.QSize(32, 16777215))
        self.lat_sec_edit.setMaxLength(2)
        self.lat_sec_edit.setObjectName(_fromUtf8("lat_sec_edit"))
        self.horizontalLayout_2.addWidget(self.lat_sec_edit)
        self.lat_sec_label = QtGui.QLabel(LocationConfigDialog)
        self.lat_sec_label.setObjectName(_fromUtf8("lat_sec_label"))
        self.horizontalLayout_2.addWidget(self.lat_sec_label)
        self.lat_dir_cb = QtGui.QComboBox(LocationConfigDialog)
        self.lat_dir_cb.setObjectName(_fromUtf8("lat_dir_cb"))
        self.lat_dir_cb.addItem(_fromUtf8(""))
        self.lat_dir_cb.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.lat_dir_cb)
        self.formLayout.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.long_label = QtGui.QLabel(LocationConfigDialog)
        self.long_label.setObjectName(_fromUtf8("long_label"))
        self.horizontalLayout_3.addWidget(self.long_label)
        self.long_deg_edit = QtGui.QLineEdit(LocationConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_deg_edit.sizePolicy().hasHeightForWidth())
        self.long_deg_edit.setSizePolicy(sizePolicy)
        self.long_deg_edit.setMinimumSize(QtCore.QSize(48, 0))
        self.long_deg_edit.setMaximumSize(QtCore.QSize(48, 16777215))
        self.long_deg_edit.setMaxLength(3)
        self.long_deg_edit.setObjectName(_fromUtf8("long_deg_edit"))
        self.horizontalLayout_3.addWidget(self.long_deg_edit)
        self.long_deg_label = QtGui.QLabel(LocationConfigDialog)
        self.long_deg_label.setObjectName(_fromUtf8("long_deg_label"))
        self.horizontalLayout_3.addWidget(self.long_deg_label)
        self.long_min_edit = QtGui.QLineEdit(LocationConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_min_edit.sizePolicy().hasHeightForWidth())
        self.long_min_edit.setSizePolicy(sizePolicy)
        self.long_min_edit.setMinimumSize(QtCore.QSize(32, 0))
        self.long_min_edit.setMaximumSize(QtCore.QSize(32, 16777215))
        self.long_min_edit.setMaxLength(2)
        self.long_min_edit.setObjectName(_fromUtf8("long_min_edit"))
        self.horizontalLayout_3.addWidget(self.long_min_edit)
        self.long_min_label = QtGui.QLabel(LocationConfigDialog)
        self.long_min_label.setObjectName(_fromUtf8("long_min_label"))
        self.horizontalLayout_3.addWidget(self.long_min_label)
        self.long_sec_edit = QtGui.QLineEdit(LocationConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_sec_edit.sizePolicy().hasHeightForWidth())
        self.long_sec_edit.setSizePolicy(sizePolicy)
        self.long_sec_edit.setMinimumSize(QtCore.QSize(32, 0))
        self.long_sec_edit.setMaximumSize(QtCore.QSize(32, 16777215))
        self.long_sec_edit.setMaxLength(2)
        self.long_sec_edit.setObjectName(_fromUtf8("long_sec_edit"))
        self.horizontalLayout_3.addWidget(self.long_sec_edit)
        self.long_sec_label = QtGui.QLabel(LocationConfigDialog)
        self.long_sec_label.setObjectName(_fromUtf8("long_sec_label"))
        self.horizontalLayout_3.addWidget(self.long_sec_label)
        self.long_dir_cb = QtGui.QComboBox(LocationConfigDialog)
        self.long_dir_cb.setObjectName(_fromUtf8("long_dir_cb"))
        self.long_dir_cb.addItem(_fromUtf8(""))
        self.long_dir_cb.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.long_dir_cb)
        self.formLayout.setLayout(2, QtGui.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(LocationConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.buttonBox)

        self.retranslateUi(LocationConfigDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), LocationConfigDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), LocationConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LocationConfigDialog)

    def retranslateUi(self, LocationConfigDialog):
        LocationConfigDialog.setWindowTitle(QtGui.QApplication.translate("LocationConfigDialog", "Configure Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loc_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lat_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.lat_deg_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.lat_min_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lat_sec_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "\'\'", None, QtGui.QApplication.UnicodeUTF8))
        self.lat_dir_cb.setItemText(0, QtGui.QApplication.translate("LocationConfigDialog", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.lat_dir_cb.setItemText(1, QtGui.QApplication.translate("LocationConfigDialog", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.long_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.long_deg_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.long_min_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "\'", None, QtGui.QApplication.UnicodeUTF8))
        self.long_sec_label.setText(QtGui.QApplication.translate("LocationConfigDialog", "\'\'", None, QtGui.QApplication.UnicodeUTF8))
        self.long_dir_cb.setItemText(0, QtGui.QApplication.translate("LocationConfigDialog", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.long_dir_cb.setItemText(1, QtGui.QApplication.translate("LocationConfigDialog", "E", None, QtGui.QApplication.UnicodeUTF8))

