# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res\ui\widgets\lunar_club_special_widget.ui'
#
# Created: Mon May 19 19:53:35 2014
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LunarClubSpecialWidget(object):
    def setupUi(self, LunarClubSpecialWidget):
        LunarClubSpecialWidget.setObjectName(_fromUtf8("LunarClubSpecialWidget"))
        LunarClubSpecialWidget.resize(227, 330)
        self.verticalLayout = QtGui.QVBoxLayout(LunarClubSpecialWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.time_from_new_moon_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.time_from_new_moon_label.setObjectName(_fromUtf8("time_from_new_moon_label"))
        self.horizontalLayout.addWidget(self.time_from_new_moon_label)
        self.time_from_new_moon_time_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.time_from_new_moon_time_label.setObjectName(_fromUtf8("time_from_new_moon_time_label"))
        self.horizontalLayout.addWidget(self.time_from_new_moon_time_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cresent_moon_waxing_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.cresent_moon_waxing_label.setObjectName(_fromUtf8("cresent_moon_waxing_label"))
        self.gridLayout.addWidget(self.cresent_moon_waxing_label, 0, 0, 1, 1)
        self.cresent_moon_waxing_indicator = QtGui.QLabel(LunarClubSpecialWidget)
        self.cresent_moon_waxing_indicator.setText(_fromUtf8(""))
        self.cresent_moon_waxing_indicator.setPixmap(QtGui.QPixmap(_fromUtf8(":/star-off.svg")))
        self.cresent_moon_waxing_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.cresent_moon_waxing_indicator.setObjectName(_fromUtf8("cresent_moon_waxing_indicator"))
        self.gridLayout.addWidget(self.cresent_moon_waxing_indicator, 0, 1, 1, 1)
        self.old_moon_in_new_moon_arms_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.old_moon_in_new_moon_arms_label.setObjectName(_fromUtf8("old_moon_in_new_moon_arms_label"))
        self.gridLayout.addWidget(self.old_moon_in_new_moon_arms_label, 1, 0, 1, 1)
        self.old_moon_in_new_moon_arms_indicator = QtGui.QLabel(LunarClubSpecialWidget)
        self.old_moon_in_new_moon_arms_indicator.setText(_fromUtf8(""))
        self.old_moon_in_new_moon_arms_indicator.setPixmap(QtGui.QPixmap(_fromUtf8(":/star-off.svg")))
        self.old_moon_in_new_moon_arms_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.old_moon_in_new_moon_arms_indicator.setObjectName(_fromUtf8("old_moon_in_new_moon_arms_indicator"))
        self.gridLayout.addWidget(self.old_moon_in_new_moon_arms_indicator, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(LunarClubSpecialWidget)
        self.line.setStyleSheet(_fromUtf8("QFrame { background-color: #ffffff; }"))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.time_to_new_moon_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.time_to_new_moon_label.setObjectName(_fromUtf8("time_to_new_moon_label"))
        self.horizontalLayout_2.addWidget(self.time_to_new_moon_label)
        self.time_to_new_moon_time_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.time_to_new_moon_time_label.setObjectName(_fromUtf8("time_to_new_moon_time_label"))
        self.horizontalLayout_2.addWidget(self.time_to_new_moon_time_label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cresent_moon_waning_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.cresent_moon_waning_label.setObjectName(_fromUtf8("cresent_moon_waning_label"))
        self.gridLayout_2.addWidget(self.cresent_moon_waning_label, 0, 0, 1, 1)
        self.cresent_moon_waning_indicator = QtGui.QLabel(LunarClubSpecialWidget)
        self.cresent_moon_waning_indicator.setText(_fromUtf8(""))
        self.cresent_moon_waning_indicator.setPixmap(QtGui.QPixmap(_fromUtf8(":/star-off.svg")))
        self.cresent_moon_waning_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.cresent_moon_waning_indicator.setObjectName(_fromUtf8("cresent_moon_waning_indicator"))
        self.gridLayout_2.addWidget(self.cresent_moon_waning_indicator, 0, 1, 1, 1)
        self.new_moon_in_old_moon_arms_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.new_moon_in_old_moon_arms_label.setObjectName(_fromUtf8("new_moon_in_old_moon_arms_label"))
        self.gridLayout_2.addWidget(self.new_moon_in_old_moon_arms_label, 1, 0, 1, 1)
        self.new_moon_in_old_moon_arms_indicator = QtGui.QLabel(LunarClubSpecialWidget)
        self.new_moon_in_old_moon_arms_indicator.setText(_fromUtf8(""))
        self.new_moon_in_old_moon_arms_indicator.setPixmap(QtGui.QPixmap(_fromUtf8(":/star-off.svg")))
        self.new_moon_in_old_moon_arms_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.new_moon_in_old_moon_arms_indicator.setObjectName(_fromUtf8("new_moon_in_old_moon_arms_indicator"))
        self.gridLayout_2.addWidget(self.new_moon_in_old_moon_arms_indicator, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtGui.QFrame(LunarClubSpecialWidget)
        self.line_2.setStyleSheet(_fromUtf8("QFrame { background-color: #ffffff; }"))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cow_jumping_over_moon_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.cow_jumping_over_moon_label.setObjectName(_fromUtf8("cow_jumping_over_moon_label"))
        self.gridLayout_3.addWidget(self.cow_jumping_over_moon_label, 0, 0, 1, 1)
        self.cow_jumping_over_moon_indicator = QtGui.QLabel(LunarClubSpecialWidget)
        self.cow_jumping_over_moon_indicator.setText(_fromUtf8(""))
        self.cow_jumping_over_moon_indicator.setPixmap(QtGui.QPixmap(_fromUtf8(":/star-off.svg")))
        self.cow_jumping_over_moon_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.cow_jumping_over_moon_indicator.setObjectName(_fromUtf8("cow_jumping_over_moon_indicator"))
        self.gridLayout_3.addWidget(self.cow_jumping_over_moon_indicator, 0, 1, 1, 1)
        self.man_in_the_moon_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.man_in_the_moon_label.setObjectName(_fromUtf8("man_in_the_moon_label"))
        self.gridLayout_3.addWidget(self.man_in_the_moon_label, 1, 0, 1, 1)
        self.man_in_the_moon_indicator = QtGui.QLabel(LunarClubSpecialWidget)
        self.man_in_the_moon_indicator.setText(_fromUtf8(""))
        self.man_in_the_moon_indicator.setPixmap(QtGui.QPixmap(_fromUtf8(":/star-off.svg")))
        self.man_in_the_moon_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.man_in_the_moon_indicator.setObjectName(_fromUtf8("man_in_the_moon_indicator"))
        self.gridLayout_3.addWidget(self.man_in_the_moon_indicator, 1, 1, 1, 1)
        self.woman_in_the_moon_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.woman_in_the_moon_label.setObjectName(_fromUtf8("woman_in_the_moon_label"))
        self.gridLayout_3.addWidget(self.woman_in_the_moon_label, 2, 0, 1, 1)
        self.woman_in_the_moon_indicator = QtGui.QLabel(LunarClubSpecialWidget)
        self.woman_in_the_moon_indicator.setText(_fromUtf8(""))
        self.woman_in_the_moon_indicator.setPixmap(QtGui.QPixmap(_fromUtf8(":/star-off.svg")))
        self.woman_in_the_moon_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.woman_in_the_moon_indicator.setObjectName(_fromUtf8("woman_in_the_moon_indicator"))
        self.gridLayout_3.addWidget(self.woman_in_the_moon_indicator, 2, 1, 1, 1)
        self.rabbit_in_the_moon_label = QtGui.QLabel(LunarClubSpecialWidget)
        self.rabbit_in_the_moon_label.setObjectName(_fromUtf8("rabbit_in_the_moon_label"))
        self.gridLayout_3.addWidget(self.rabbit_in_the_moon_label, 3, 0, 1, 1)
        self.rabbit_in_the_moon_indicator = QtGui.QLabel(LunarClubSpecialWidget)
        self.rabbit_in_the_moon_indicator.setText(_fromUtf8(""))
        self.rabbit_in_the_moon_indicator.setPixmap(QtGui.QPixmap(_fromUtf8(":/star-off.svg")))
        self.rabbit_in_the_moon_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.rabbit_in_the_moon_indicator.setObjectName(_fromUtf8("rabbit_in_the_moon_indicator"))
        self.gridLayout_3.addWidget(self.rabbit_in_the_moon_indicator, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(LunarClubSpecialWidget)
        QtCore.QMetaObject.connectSlotsByName(LunarClubSpecialWidget)

    def retranslateUi(self, LunarClubSpecialWidget):
        LunarClubSpecialWidget.setWindowTitle(QtGui.QApplication.translate("LunarClubSpecialWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.time_from_new_moon_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Time from New Moon:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_from_new_moon_time_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.cresent_moon_waxing_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Cresent Moon, Waxing", None, QtGui.QApplication.UnicodeUTF8))
        self.old_moon_in_new_moon_arms_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Old Moon in New Moon\'s Arms", None, QtGui.QApplication.UnicodeUTF8))
        self.time_to_new_moon_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Time to New Moon:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_to_new_moon_time_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.cresent_moon_waning_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Cresent Moon, Waning", None, QtGui.QApplication.UnicodeUTF8))
        self.new_moon_in_old_moon_arms_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "New Moon in Old Moon\'s Arms", None, QtGui.QApplication.UnicodeUTF8))
        self.cow_jumping_over_moon_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Cow Jumping Over the Moon", None, QtGui.QApplication.UnicodeUTF8))
        self.man_in_the_moon_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Man in the Moon", None, QtGui.QApplication.UnicodeUTF8))
        self.woman_in_the_moon_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Woman in the Moon", None, QtGui.QApplication.UnicodeUTF8))
        self.rabbit_in_the_moon_label.setText(QtGui.QApplication.translate("LunarClubSpecialWidget", "Rabbit in the Moon", None, QtGui.QApplication.UnicodeUTF8))

from . import widget_resources_rc
