# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res\ui\widgets\moon_info_tab.ui'
#
# Created: Sun May 18 12:08:25 2014
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MoonInfoTabWidget(object):
    def setupUi(self, MoonInfoTabWidget):
        MoonInfoTabWidget.setObjectName(_fromUtf8("MoonInfoTabWidget"))
        MoonInfoTabWidget.resize(417, 508)
        MoonInfoTabWidget.setWindowTitle(_fromUtf8(""))
        self.gridLayout_2 = QtGui.QGridLayout(MoonInfoTabWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.last_obs_label = QtGui.QLabel(MoonInfoTabWidget)
        self.last_obs_label.setObjectName(_fromUtf8("last_obs_label"))
        self.horizontalLayout_10.addWidget(self.last_obs_label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.local_date_label = QtGui.QLabel(MoonInfoTabWidget)
        self.local_date_label.setObjectName(_fromUtf8("local_date_label"))
        self.horizontalLayout_9.addWidget(self.local_date_label)
        self.local_date_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.local_date_edit.setText(_fromUtf8(""))
        self.local_date_edit.setObjectName(_fromUtf8("local_date_edit"))
        self.horizontalLayout_9.addWidget(self.local_date_edit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.utc_date_label = QtGui.QLabel(MoonInfoTabWidget)
        self.utc_date_label.setObjectName(_fromUtf8("utc_date_label"))
        self.horizontalLayout.addWidget(self.utc_date_label)
        self.utc_date_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.utc_date_edit.setText(_fromUtf8(""))
        self.utc_date_edit.setObjectName(_fromUtf8("utc_date_edit"))
        self.horizontalLayout.addWidget(self.utc_date_edit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.moon_phase_label = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_phase_label.setObjectName(_fromUtf8("moon_phase_label"))
        self.horizontalLayout_6.addWidget(self.moon_phase_label)
        self.moon_phase_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_phase_edit.setText(_fromUtf8(""))
        self.moon_phase_edit.setObjectName(_fromUtf8("moon_phase_edit"))
        self.horizontalLayout_6.addWidget(self.moon_phase_edit)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.moon_illum_label = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_illum_label.setObjectName(_fromUtf8("moon_illum_label"))
        self.horizontalLayout_3.addWidget(self.moon_illum_label)
        self.moon_illum_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_illum_edit.setText(_fromUtf8(""))
        self.moon_illum_edit.setObjectName(_fromUtf8("moon_illum_edit"))
        self.horizontalLayout_3.addWidget(self.moon_illum_edit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.moon_colong_label = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_colong_label.setObjectName(_fromUtf8("moon_colong_label"))
        self.horizontalLayout_4.addWidget(self.moon_colong_label)
        self.moon_colong_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_colong_edit.setText(_fromUtf8(""))
        self.moon_colong_edit.setObjectName(_fromUtf8("moon_colong_edit"))
        self.horizontalLayout_4.addWidget(self.moon_colong_edit)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.moon_age_label = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_age_label.setObjectName(_fromUtf8("moon_age_label"))
        self.horizontalLayout_5.addWidget(self.moon_age_label)
        self.moon_age_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_age_edit.setText(_fromUtf8(""))
        self.moon_age_edit.setObjectName(_fromUtf8("moon_age_edit"))
        self.horizontalLayout_5.addWidget(self.moon_age_edit)
        self.moon_age_units_label = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_age_units_label.setObjectName(_fromUtf8("moon_age_units_label"))
        self.horizontalLayout_5.addWidget(self.moon_age_units_label)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.moon_libration_lat_label = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_libration_lat_label.setObjectName(_fromUtf8("moon_libration_lat_label"))
        self.horizontalLayout_7.addWidget(self.moon_libration_lat_label)
        self.moon_libration_lat_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_libration_lat_edit.setText(_fromUtf8(""))
        self.moon_libration_lat_edit.setObjectName(_fromUtf8("moon_libration_lat_edit"))
        self.horizontalLayout_7.addWidget(self.moon_libration_lat_edit)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 7, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.moon_libration_long_label = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_libration_long_label.setObjectName(_fromUtf8("moon_libration_long_label"))
        self.horizontalLayout_8.addWidget(self.moon_libration_long_label)
        self.moon_libration_long_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.moon_libration_long_edit.setText(_fromUtf8(""))
        self.moon_libration_long_edit.setObjectName(_fromUtf8("moon_libration_long_edit"))
        self.horizontalLayout_8.addWidget(self.moon_libration_long_edit)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 8, 0, 1, 1)
        self.frame = QtGui.QFrame(MoonInfoTabWidget)
        self.frame.setStyleSheet(_fromUtf8("QFrame { background-color: #ffffff; }"))
        self.frame.setFrameShape(QtGui.QFrame.HLine)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2.addWidget(self.frame, 9, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.next_phase_dates_label = QtGui.QLabel(MoonInfoTabWidget)
        self.next_phase_dates_label.setObjectName(_fromUtf8("next_phase_dates_label"))
        self.horizontalLayout_11.addWidget(self.next_phase_dates_label)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 10, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.first_phase_icon = QtGui.QLabel(MoonInfoTabWidget)
        self.first_phase_icon.setObjectName(_fromUtf8("first_phase_icon"))
        self.gridLayout.addWidget(self.first_phase_icon, 0, 0, 1, 1)
        self.first_phase_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.first_phase_edit.setObjectName(_fromUtf8("first_phase_edit"))
        self.gridLayout.addWidget(self.first_phase_edit, 0, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 0, 2, 1, 1)
        self.second_phase_icon = QtGui.QLabel(MoonInfoTabWidget)
        self.second_phase_icon.setObjectName(_fromUtf8("second_phase_icon"))
        self.gridLayout.addWidget(self.second_phase_icon, 1, 0, 1, 1)
        self.second_phase_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.second_phase_edit.setObjectName(_fromUtf8("second_phase_edit"))
        self.gridLayout.addWidget(self.second_phase_edit, 1, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 1, 2, 1, 1)
        self.third_phase_icon = QtGui.QLabel(MoonInfoTabWidget)
        self.third_phase_icon.setObjectName(_fromUtf8("third_phase_icon"))
        self.gridLayout.addWidget(self.third_phase_icon, 2, 0, 1, 1)
        self.third_phase_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.third_phase_edit.setObjectName(_fromUtf8("third_phase_edit"))
        self.gridLayout.addWidget(self.third_phase_edit, 2, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 2, 2, 1, 1)
        self.fourth_phase_icon = QtGui.QLabel(MoonInfoTabWidget)
        self.fourth_phase_icon.setObjectName(_fromUtf8("fourth_phase_icon"))
        self.gridLayout.addWidget(self.fourth_phase_icon, 3, 0, 1, 1)
        self.fourth_phase_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.fourth_phase_edit.setObjectName(_fromUtf8("fourth_phase_edit"))
        self.gridLayout.addWidget(self.fourth_phase_edit, 3, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 11, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 135, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 12, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(MoonInfoTabWidget)
        self.frame_2.setStyleSheet(_fromUtf8("QFrame { background-color: #ffffff; }"))
        self.frame_2.setFrameShape(QtGui.QFrame.HLine)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2.addWidget(self.frame_2, 13, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.location_label = QtGui.QLabel(MoonInfoTabWidget)
        self.location_label.setObjectName(_fromUtf8("location_label"))
        self.horizontalLayout_2.addWidget(self.location_label)
        self.location_edit = QtGui.QLabel(MoonInfoTabWidget)
        self.location_edit.setText(_fromUtf8(""))
        self.location_edit.setObjectName(_fromUtf8("location_edit"))
        self.horizontalLayout_2.addWidget(self.location_edit)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 14, 0, 1, 1)

        self.retranslateUi(MoonInfoTabWidget)
        QtCore.QMetaObject.connectSlotsByName(MoonInfoTabWidget)

    def retranslateUi(self, MoonInfoTabWidget):
        self.last_obs_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Last Observation", None, QtGui.QApplication.UnicodeUTF8))
        self.local_date_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.utc_date_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Date (UTC):", None, QtGui.QApplication.UnicodeUTF8))
        self.moon_phase_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Phase:", None, QtGui.QApplication.UnicodeUTF8))
        self.moon_illum_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Illumination:", None, QtGui.QApplication.UnicodeUTF8))
        self.moon_colong_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Colongitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.moon_age_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Age:", None, QtGui.QApplication.UnicodeUTF8))
        self.moon_age_units_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "days", None, QtGui.QApplication.UnicodeUTF8))
        self.moon_libration_lat_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Libration Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.moon_libration_long_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Libration Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.next_phase_dates_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Next Phase Dates", None, QtGui.QApplication.UnicodeUTF8))
        self.first_phase_icon.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.first_phase_edit.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.second_phase_icon.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.second_phase_edit.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.third_phase_icon.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.third_phase_edit.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.fourth_phase_icon.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.fourth_phase_edit.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.location_label.setText(QtGui.QApplication.translate("MoonInfoTabWidget", "Location:", None, QtGui.QApplication.UnicodeUTF8))

