__version__ = "0.1"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '213c1f69e0cdae4243bf0c4d3d9a89a6284f8b07'
__git_head_subject__ = 'Finished release v0.1.'
__git_head_message__ = ''
__git_dirty_diff__ = ''