__version__ = "0.1.1"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "yalon@infinidat.com"
__git_branch__ = '(detached from v0.1.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '3eb42db3c196d7aaf77f505254ccc26feab76160'
__git_head_subject__ = 'Finished release v0.1.1.'
__git_head_message__ = ''
__git_dirty_diff__ = ''