
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5'
version_full = 'fb742f1bac59804abdb067319e3d16fa9e1d20fa'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

