
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.5'
version_full = 'a437113d8a6e1ad2c3743e0e60ad996ff9bd3367'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

