
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(src/python/twitter/common/python/BUILD:python)

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': "Twitter's Python packaging toolchain.",
    'entry_points': {   'console_scripts': [   'pex = twitter.common.python.bin.pex:main']},
    'install_requires': ['wheel', 'setuptools>=1'],
    'license': 'Apache License, Version 2.0',
    'long_description': '\nTwitter\'s Python packaging libraries and toolchain for fetching,\nbuilding and packaging dependencies into .pex ("Python EXecutable")\nvirtualized environments.\n',
    'name': 'twitter.common.python',
    'namespace_packages': ['twitter', 'twitter.common'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': [   'twitter',
                    'twitter.common',
                    'twitter.common.python',
                    'twitter.common.python.bin',
                    'twitter.common.python.http'],
    'url': 'https://github.com/twitter/commons/tree/master/src/python/twitter/common/python',
    'version': '0.5.8',
    'zip_safe': True}
)
