// Generated by CoffeeScript 1.7.1
(function() {
  var appFltr;

  appFltr = angular.module('appFltr', []);

  appFltr.filter('capitalcase', function() {
    var filter;
    filter = function(input) {
      return input.substring(0, 1).toUpperCase() + input.substring(1);
    };
    return filter;
  });

  appFltr.filter('titlecase', function() {
    var filter;
    filter = function(input) {
      var chunk, chunks, i, _i, _len;
      chunks = input.split(" ");
      for (i = _i = 0, _len = chunks.length; _i < _len; i = ++_i) {
        chunk = chunks[i];
        chunks[i] = chunk.substring(0, 1).toUpperCase() + chunk.substring(1);
      }
      return chunks.join(" ");
    };
    return filter;
  });

  appFltr.filter('pagerize', function() {
    var filter;
    filter = function(input, pager) {
      var end, output, start;
      if (pager == null) {
        return input;
      }
      pager.itemCount = input.length;
      start = pager.itemOffset();
      end = start + pager.perPage;
      output = input.slice(start, end);
      return output;
    };
    return filter;
  });

  appFltr.filter('truncate', function() {
    var filter;
    filter = function(text, length, end) {
      var retval;
      if (isNaN(length)) {
        length = 20;
      }
      if (end == null) {
        end = '...';
      }
      retval = null;
      if (text.length < length || text.lenght - end.length <= length) {
        retval = text;
      } else {
        retval = text.substring(0, length - end.length) + end;
      }
      return retval;
    };
    return filter;
  });

}).call(this);
