/*
 * Compile it with the code generated by opengeode
 * using the following command-line:
 * gcc ping.c integrate-ping.c -DOPENGEODEDEBUG=1
 */

#include "ping_process.h"
#include <stdio.h>

int main ()
{
   ping_data_t input;
   ping_data_t output;

   input.state = PING_START;

   printf ("State        = %d\n", input.state);
   pingprocess (&input, &output);
   printf ("New State    = %d\n", output.state);

   input = output;

   printf ("State        = %d\n", input.state);
   pingprocess (&input, &output);
   printf ("New State    = %d\n", output.state);
   printf ("Output ping  = %d\n", output.outputs.ping_snd_ping);

   input = output;
   input.input.value    = ping_activation;
   printf ("State        = %d\n", input.state);
   pingprocess (&input, &output);
   printf ("New State    = %d\n", output.state);
   printf ("Output ping  = %d\n", output.outputs.ping_snd_ping);


   return 0;
}
