
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.4'
version_full = '902aea9a9a4863a87d82227299964ea4317a0c33'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

