
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.3-4-g1e456b0'
version_full = '1e456b0fff46001641a736bc5932314e9d00b1bc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

