#ifndef BOOST_SIMD_TOOLBOX_OPERATOR_INCLUDE_FUNCTIONS_SCALAR_IS_GREATER_EQUAL_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_OPERATOR_INCLUDE_FUNCTIONS_SCALAR_IS_GREATER_EQUAL_HPP_INCLUDED

#include <boost/simd/toolbox/operator/functions/is_greater_equal.hpp>
#include <boost/simd/toolbox/operator/functions/scalar/is_greater_equal.hpp>

#endif
