#ifndef BOOST_SIMD_TOOLBOX_OPERATOR_INCLUDE_FUNCTIONS_SCALAR_UNALIGNED_LOAD_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_OPERATOR_INCLUDE_FUNCTIONS_SCALAR_UNALIGNED_LOAD_HPP_INCLUDED

#include <boost/simd/toolbox/operator/functions/unaligned_load.hpp>
#include <boost/simd/toolbox/operator/functions/scalar/unaligned_load.hpp>

#endif
