#ifndef BOOST_SIMD_TOOLBOX_OPERATOR_INCLUDE_FUNCTIONS_SCALAR_UNALIGNED_STORE_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_OPERATOR_INCLUDE_FUNCTIONS_SCALAR_UNALIGNED_STORE_HPP_INCLUDED

#include <boost/simd/toolbox/operator/functions/unaligned_store.hpp>
#include <boost/simd/toolbox/operator/functions/scalar/unaligned_store.hpp>

#endif
