
# This file was generated by 'versioneer.py' (0.10+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.0'
version_full = '6a06358fa2a152147d929c73892916fd3aaa5130'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

