
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.0'
version_full = 'fa2b11ff99c241a1ef775eb9e655ca0f3c73b152'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

