
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2'
version_full = '8ba3db2d90e2ad13af6f1d78c44ff0f4601dc488'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

