
# This file was generated by 'versioneer.py' (0.9) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.6'
version_full = '7a81b5613850b775528f0d05b1dd2d50b04e0068'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

