
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.2-dirty'
version_full = 'c23bb55c26b758c90e4ed6b000d59335d7072600-dirty'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

