#
# Copyright (c) 2013, 2014
#  Adam Tauno Williams <awilliam@whitemice.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE
#
AUTOTHUMB_NAIL_REQUEST = 200
AUTOTHUMB_NAIL_CREATED = 201
AUTOTHUMB_NAIL_FAILED = 202

DOCUMENT_COLLECT_REQUEST = 300
DOCUMENT_COLLECT_DISCARDED = 301
DOCUMENT_COLLECT_FAILED = 302
DOCUMENT_COLLECT_COMPLETED = 303

DOCUMENT_BURST_REQUEST = 400
DOCUMENT_BURST_COMPLETED = 401
DOCUMENT_BURST_FAILED = 402
DOCUMENT_BURST_DISCARDED = 403

DOCUMENT_DELETED = 500

DOCUMENT_AUTOFILE_REQUEST = 600
DOCUMENT_AUTOFILE_COMPLETED = 601
DOCUMENT_AUTOFILE_FAILED = 602
DOCUMENT_AUTOFILE_DISCARDED = 603

DOCUMENT_SPECIAL_PROCESSING = 700
DOCUMENT_SPECIAL_DISCARDED = 701
DOCUMENT_SPECIAL_FAILED = 702
DOCUMENT_SPECIAL_COMPLETED = 703

DOCUMENT_UNCOLLECT_REQUEST = 800
DOCUMENT_UNCOLLECT_DISCARDED = 801
DOCUMENT_UNCOLLECT_FAILED = 802
DOCUMENT_UNCOLLECT_COMPLETED = 803

ENQUEUE_PROCESS = 1000
