
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.1'
version_full = '5ec54b101691bc007b762f29aa6ba2bcbbafbdfa'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

