__version__ = "0.1.30"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.1.30)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '0936ca4bb115ed83942a3af610705d0904b26246'
__git_head_subject__ = 'buildout.cfg: changed isolated python version to v2.7.6.9'
__git_head_message__ = ''
__git_dirty_diff__ = ''