
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.5'
version_full = '37dddc9a2b15f3c4bdd47376cca51a41f44838ff'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

