
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2'
version_full = '03b4ed07d1c55770d9c5b0ed8e7d42dd08f80272'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

