#ifndef NT2_TOOLBOX_PREDICATES_INCLUDE_FUNCTIONS_SCALAR_IS_NOT_INFINITE_HPP_INCLUDED
#define NT2_TOOLBOX_PREDICATES_INCLUDE_FUNCTIONS_SCALAR_IS_NOT_INFINITE_HPP_INCLUDED

#include <nt2/toolbox/predicates/functions/is_not_infinite.hpp>
#include <boost/simd/toolbox/predicates/functions/scalar/is_not_infinite.hpp>

#endif
