#ifndef NT2_TOOLBOX_PREDICATES_INCLUDE_FUNCTIONS_SCALAR_IS_NOT_GREATER_EQUAL_HPP_INCLUDED
#define NT2_TOOLBOX_PREDICATES_INCLUDE_FUNCTIONS_SCALAR_IS_NOT_GREATER_EQUAL_HPP_INCLUDED

#include <nt2/toolbox/predicates/functions/is_not_greater_equal.hpp>
#include <boost/simd/toolbox/predicates/functions/scalar/is_not_greater_equal.hpp>

#endif
