
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2'
version_full = 'c621fa7322b4f8151eb37b27f8aeae563cf6bd63'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

