
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.12.6'
version_full = '83021ebbb7a4f7c1107c64ddfd05f6a5b7456c8a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

