__version__ = "0.0.7"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "tal.yalon@gmail.com"
__git_branch__ = '(detached from v0.0.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '67027d7fe30e8f499d888d073855d9171f2e271d'
__git_head_subject__ = 'Finished release v0.0.7.'
__git_head_message__ = ''
__git_dirty_diff__ = ''