
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.0'
version_full = 'aa093d286159bb7147fbdf7a7e7be59c333e0322'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

