
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.10'
version_full = 'c4762bb7b4ff90c471b8f549637fc224380c3f42'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

