
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.9'
version_full = '1a8e5168caeb6b5009ad1346d162d3632b3862a7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

