#ifndef NT2_TOOLBOX_BOOST_MATH_INCLUDE_FUNCTIONS_SIMD_IBETA_DERIVATIVE_HPP_INCLUDED
#define NT2_TOOLBOX_BOOST_MATH_INCLUDE_FUNCTIONS_SIMD_IBETA_DERIVATIVE_HPP_INCLUDED

#include <nt2/toolbox/boost_math/functions/ibeta_derivative.hpp>
#include <nt2/toolbox/boost_math/functions/scalar/ibeta_derivative.hpp>

#endif
