#ifndef NT2_TOOLBOX_BOOST_MATH_INCLUDE_FUNCTIONS_SIMD_TGAMMA_DELTA_RATIO_HPP_INCLUDED
#define NT2_TOOLBOX_BOOST_MATH_INCLUDE_FUNCTIONS_SIMD_TGAMMA_DELTA_RATIO_HPP_INCLUDED

#include <nt2/toolbox/boost_math/functions/tgamma_delta_ratio.hpp>
#include <nt2/toolbox/boost_math/functions/scalar/tgamma_delta_ratio.hpp>

#endif
