
# This file was generated by 'versioneer.py' (0.10+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0c1'
version_full = '307bd5d39f2d06420742d1c632d5283dd10eb368'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

