#ifndef NT2_TOOLBOX_LINALG_FUNCTIONS_HPP_INCLUDED
#define NT2_TOOLBOX_LINALG_FUNCTIONS_HPP_INCLUDED

#include <nt2/toolbox/linalg/include/functions/balance.hpp>
#include <nt2/toolbox/linalg/include/functions/binomial.hpp>
#include <nt2/toolbox/linalg/include/functions/cauchy.hpp>
#include <nt2/toolbox/linalg/include/functions/chebspec.hpp>
#include <nt2/toolbox/linalg/include/functions/chebvand.hpp>
#include <nt2/toolbox/linalg/include/functions/chol.hpp>
#include <nt2/toolbox/linalg/include/functions/chol_solve.hpp>
#include <nt2/toolbox/linalg/include/functions/chow.hpp>
#include <nt2/toolbox/linalg/include/functions/circul.hpp>
#include <nt2/toolbox/linalg/include/functions/clement.hpp>
#include <nt2/toolbox/linalg/include/functions/compar.hpp>
#include <nt2/toolbox/linalg/include/functions/cond.hpp>
#include <nt2/toolbox/linalg/include/functions/cov.hpp>
#include <nt2/toolbox/linalg/include/functions/expm.hpp>
#include <nt2/toolbox/linalg/include/functions/full_lu_solve.hpp>
#include <nt2/toolbox/linalg/include/functions/full_qr_solve.hpp>
#include <nt2/toolbox/linalg/include/functions/geneig.hpp>
#include <nt2/toolbox/linalg/include/functions/hilb.hpp>
#include <nt2/toolbox/linalg/include/functions/impower.hpp>
#include <nt2/toolbox/linalg/include/functions/inv.hpp>
#include <nt2/toolbox/linalg/include/functions/invhilb.hpp>
#include <nt2/toolbox/linalg/include/functions/linsolve.hpp>
#include <nt2/toolbox/linalg/include/functions/lsq_lse_solve.hpp>
#include <nt2/toolbox/linalg/include/functions/lu.hpp>
#include <nt2/toolbox/linalg/include/functions/magic.hpp>
#include <nt2/toolbox/linalg/include/functions/mpower.hpp>
#include <nt2/toolbox/linalg/include/functions/mtimes.hpp>
#include <nt2/toolbox/linalg/include/functions/norm.hpp>
#include <nt2/toolbox/linalg/include/functions/normest.hpp>
#include <nt2/toolbox/linalg/include/functions/null.hpp>
#include <nt2/toolbox/linalg/include/functions/options.hpp>
#include <nt2/toolbox/linalg/include/functions/orth.hpp>
#include <nt2/toolbox/linalg/include/functions/pascal.hpp>
#include <nt2/toolbox/linalg/include/functions/pinv.hpp>
#include <nt2/toolbox/linalg/include/functions/planerot.hpp>
#include <nt2/toolbox/linalg/include/functions/poly.hpp>
#include <nt2/toolbox/linalg/include/functions/qr.hpp>
#include <nt2/toolbox/linalg/include/functions/rank.hpp>
#include <nt2/toolbox/linalg/include/functions/rot90.hpp>
#include <nt2/toolbox/linalg/include/functions/rref.hpp>
#include <nt2/toolbox/linalg/include/functions/schur.hpp>
#include <nt2/toolbox/linalg/include/functions/sqrtm.hpp>
#include <nt2/toolbox/linalg/include/functions/svd.hpp>
#include <nt2/toolbox/linalg/include/functions/svd_solve.hpp>
#include <nt2/toolbox/linalg/include/functions/symeig.hpp>
#include <nt2/toolbox/linalg/include/functions/tksolve.hpp>
#include <nt2/toolbox/linalg/include/functions/toeplitz.hpp>
#include <nt2/toolbox/linalg/include/functions/tr_solve.hpp>
#include <nt2/toolbox/linalg/include/functions/trace.hpp>
#include <nt2/toolbox/linalg/include/functions/tridiag.hpp>
#include <nt2/toolbox/linalg/include/functions/vandermonde.hpp>
#include <nt2/toolbox/linalg/include/functions/vecnorm.hpp>

#endif
