__version__ = "0.0.8"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.0.8)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '149cc20e0c71a9ba056684d606723ca4e39034bc'
__git_head_subject__ = 'update homepage'
__git_head_message__ = ''
__git_dirty_diff__ = ''