
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.3'
version_full = '2ff0556f8abdcd7007a1a351a6018c578c20cd0d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

