#ifndef NT2_INCLUDE_FUNCTIONS_ALMOST_LESS_OR_EQUAL_HPP_INCLUDED
#define NT2_INCLUDE_FUNCTIONS_ALMOST_LESS_OR_EQUAL_HPP_INCLUDED

#include <nt2/toolbox/fuzzy/include/functions/almost_less_or_equal.hpp>

#endif
