__version__ = "0.6.25"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.6.25)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ce5806ebd7f0f6d38b74a0914dd45056fb91de8a'
__git_head_subject__ = 'Finished release v0.6.25.'
__git_head_message__ = '* release/v0.6.25:\n  STORAGEMODEL-228 fixing pack_json\n  STORAGEMODEL-288 fixing unpack_json\n  STORAGEMODEL-288 adding json_field'
__git_dirty_diff__ = ''