__version__ = "0.2.4"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.2.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '446996f0b94d3f430e0a61a9fe72c29a53f49e2a'
__git_head_subject__ = 'print param name as message along with file list for filename arguments'
__git_head_message__ = ''
__git_dirty_diff__ = ''