#ifndef BOOST_SIMD_TOOLBOX_SWAR_INCLUDE_FUNCTIONS_SCALAR_DEINTERLEAVE_SECOND_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_SWAR_INCLUDE_FUNCTIONS_SCALAR_DEINTERLEAVE_SECOND_HPP_INCLUDED

#include <boost/simd/toolbox/swar/functions/deinterleave_second.hpp>
#include <boost/simd/toolbox/swar/functions/scalar/deinterleave_second.hpp>

#endif
