# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='src/kRPC/Schema/KRPC.proto',
  package='KRPC',
  serialized_pb='\n\x1asrc/kRPC/Schema/KRPC.proto\x12\x04KRPC\"P\n\x07Request\x12\x0f\n\x07service\x18\x01 \x02(\t\x12\x11\n\tprocedure\x18\x02 \x02(\t\x12!\n\targuments\x18\x03 \x03(\x0b\x32\x0e.KRPC.Argument\"+\n\x08\x41rgument\x12\x10\n\x08position\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\x0c\"=\n\x08Response\x12\x0c\n\x04time\x18\x01 \x02(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x14\n\x0creturn_value\x18\x03 \x01(\x0c\"+\n\x08Services\x12\x1f\n\x08services\x18\x01 \x03(\x0b\x32\r.KRPC.Service\"\x83\x01\n\x07Service\x12\x0c\n\x04name\x18\x01 \x02(\t\x12#\n\nprocedures\x18\x02 \x03(\x0b\x32\x0f.KRPC.Procedure\x12\x1c\n\x07\x63lasses\x18\x03 \x03(\x0b\x32\x0b.KRPC.Class\x12\'\n\x0c\x65numerations\x18\x04 \x03(\x0b\x32\x11.KRPC.Enumeration\"g\n\tProcedure\x12\x0c\n\x04name\x18\x01 \x02(\t\x12#\n\nparameters\x18\x02 \x03(\x0b\x32\x0f.KRPC.Parameter\x12\x13\n\x0breturn_type\x18\x03 \x01(\t\x12\x12\n\nattributes\x18\x04 \x03(\t\"A\n\tParameter\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x18\n\x10\x64\x65\x66\x61ult_argument\x18\x03 \x01(\x0c\"\x15\n\x05\x43lass\x12\x0c\n\x04name\x18\x01 \x02(\t\"C\n\x0b\x45numeration\x12\x0c\n\x04name\x18\x01 \x02(\t\x12&\n\x06values\x18\x02 \x03(\x0b\x32\x16.KRPC.EnumerationValue\"/\n\x10\x45numerationValue\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x05\"\x19\n\x06Status\x12\x0f\n\x07version\x18\x01 \x02(\t')




_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='KRPC.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service', full_name='KRPC.Request.service', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='procedure', full_name='KRPC.Request.procedure', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arguments', full_name='KRPC.Request.arguments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=116,
)


_ARGUMENT = descriptor.Descriptor(
  name='Argument',
  full_name='KRPC.Argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='position', full_name='KRPC.Argument.position', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='KRPC.Argument.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=118,
  serialized_end=161,
)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='KRPC.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='KRPC.Response.time', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='KRPC.Response.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='return_value', full_name='KRPC.Response.return_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=163,
  serialized_end=224,
)


_SERVICES = descriptor.Descriptor(
  name='Services',
  full_name='KRPC.Services',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='services', full_name='KRPC.Services.services', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=226,
  serialized_end=269,
)


_SERVICE = descriptor.Descriptor(
  name='Service',
  full_name='KRPC.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='KRPC.Service.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='procedures', full_name='KRPC.Service.procedures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='classes', full_name='KRPC.Service.classes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enumerations', full_name='KRPC.Service.enumerations', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=272,
  serialized_end=403,
)


_PROCEDURE = descriptor.Descriptor(
  name='Procedure',
  full_name='KRPC.Procedure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='KRPC.Procedure.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parameters', full_name='KRPC.Procedure.parameters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='return_type', full_name='KRPC.Procedure.return_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attributes', full_name='KRPC.Procedure.attributes', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=405,
  serialized_end=508,
)


_PARAMETER = descriptor.Descriptor(
  name='Parameter',
  full_name='KRPC.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='KRPC.Parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='KRPC.Parameter.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_argument', full_name='KRPC.Parameter.default_argument', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=510,
  serialized_end=575,
)


_CLASS = descriptor.Descriptor(
  name='Class',
  full_name='KRPC.Class',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='KRPC.Class.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=577,
  serialized_end=598,
)


_ENUMERATION = descriptor.Descriptor(
  name='Enumeration',
  full_name='KRPC.Enumeration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='KRPC.Enumeration.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='values', full_name='KRPC.Enumeration.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=600,
  serialized_end=667,
)


_ENUMERATIONVALUE = descriptor.Descriptor(
  name='EnumerationValue',
  full_name='KRPC.EnumerationValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='KRPC.EnumerationValue.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='KRPC.EnumerationValue.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=669,
  serialized_end=716,
)


_STATUS = descriptor.Descriptor(
  name='Status',
  full_name='KRPC.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='KRPC.Status.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=718,
  serialized_end=743,
)

_REQUEST.fields_by_name['arguments'].message_type = _ARGUMENT
_SERVICES.fields_by_name['services'].message_type = _SERVICE
_SERVICE.fields_by_name['procedures'].message_type = _PROCEDURE
_SERVICE.fields_by_name['classes'].message_type = _CLASS
_SERVICE.fields_by_name['enumerations'].message_type = _ENUMERATION
_PROCEDURE.fields_by_name['parameters'].message_type = _PARAMETER
_ENUMERATION.fields_by_name['values'].message_type = _ENUMERATIONVALUE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Argument'] = _ARGUMENT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Services'] = _SERVICES
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['Procedure'] = _PROCEDURE
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['Class'] = _CLASS
DESCRIPTOR.message_types_by_name['Enumeration'] = _ENUMERATION
DESCRIPTOR.message_types_by_name['EnumerationValue'] = _ENUMERATIONVALUE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:KRPC.Request)

class Argument(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARGUMENT
  
  # @@protoc_insertion_point(class_scope:KRPC.Argument)

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE
  
  # @@protoc_insertion_point(class_scope:KRPC.Response)

class Services(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICES
  
  # @@protoc_insertion_point(class_scope:KRPC.Services)

class Service(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICE
  
  # @@protoc_insertion_point(class_scope:KRPC.Service)

class Procedure(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROCEDURE
  
  # @@protoc_insertion_point(class_scope:KRPC.Procedure)

class Parameter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAMETER
  
  # @@protoc_insertion_point(class_scope:KRPC.Parameter)

class Class(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLASS
  
  # @@protoc_insertion_point(class_scope:KRPC.Class)

class Enumeration(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENUMERATION
  
  # @@protoc_insertion_point(class_scope:KRPC.Enumeration)

class EnumerationValue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENUMERATIONVALUE
  
  # @@protoc_insertion_point(class_scope:KRPC.EnumerationValue)

class Status(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUS
  
  # @@protoc_insertion_point(class_scope:KRPC.Status)

# @@protoc_insertion_point(module_scope)
