__version__ = "0.5"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.5)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'cc12f39e7cf8f2d133b0de2345d0585e39ce355f'
__git_head_subject__ = 'Finished release v0.5.'
__git_head_message__ = ''
__git_dirty_diff__ = ''