
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.2'
version_full = '486e458c9acdb79807ccc8146295cec39e4103e0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

