
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.1'
version_full = '84a937337738be9ec5da202bfef6a4702aa5d1d3'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

