__version__ = "0.2.13"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.2.13)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a43990c5e8cad7197991baa28264a486c39fb65a'
__git_head_subject__ = 'Finished release v0.2.13.'
__git_head_message__ = ''
__git_dirty_diff__ = ''