#ifndef BOOST_SIMD_INCLUDE_FUNCTIONS_SCALAR_UNALIGNED_STORE_HPP_INCLUDED
#define BOOST_SIMD_INCLUDE_FUNCTIONS_SCALAR_UNALIGNED_STORE_HPP_INCLUDED

#include <boost/simd/toolbox/operator/include/functions/scalar/unaligned_store.hpp>

#endif
