
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.12.5'
version_full = '749b518b90140b64aa711f33460525222339e000'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

