#ifndef BOOST_SIMD_TOOLBOX_REDUCTION_INCLUDE_FUNCTIONS_SCALAR_COMPARE_NOT_EQUAL_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_REDUCTION_INCLUDE_FUNCTIONS_SCALAR_COMPARE_NOT_EQUAL_HPP_INCLUDED

#include <boost/simd/toolbox/reduction/functions/compare_not_equal.hpp>
#include <boost/simd/toolbox/reduction/functions/scalar/compare_not_equal.hpp>

#endif
