#ifndef NT2_CORE_FUNCTIONS_HPP_INCLUDED
#define NT2_CORE_FUNCTIONS_HPP_INCLUDED

#include <nt2/core/include/functions/adjfun.hpp>
#include <nt2/core/include/functions/aggregate.hpp>
#include <nt2/core/include/functions/along.hpp>
#include <nt2/core/include/functions/arecatcompatible.hpp>
#include <nt2/core/include/functions/arecrosscompatible.hpp>
#include <nt2/core/include/functions/as_size.hpp>
#include <nt2/core/include/functions/asum1.hpp>
#include <nt2/core/include/functions/asum2.hpp>
#include <nt2/core/include/functions/asump.hpp>
#include <nt2/core/include/functions/band.hpp>
#include <nt2/core/include/functions/blkdiag.hpp>
#include <nt2/core/include/functions/bsxfun.hpp>
#include <nt2/core/include/functions/cast.hpp>
#include <nt2/core/include/functions/cat.hpp>
#include <nt2/core/include/functions/cdiff.hpp>
#include <nt2/core/include/functions/center.hpp>
#include <nt2/core/include/functions/cic.hpp>
#include <nt2/core/include/functions/cif.hpp>
#include <nt2/core/include/functions/class.hpp>
#include <nt2/core/include/functions/colon.hpp>
#include <nt2/core/include/functions/cols.hpp>
#include <nt2/core/include/functions/colvect.hpp>
#include <nt2/core/include/functions/cons.hpp>
#include <nt2/core/include/functions/construct.hpp>
#include <nt2/core/include/functions/depth.hpp>
#include <nt2/core/include/functions/diag_of.hpp>
#include <nt2/core/include/functions/diff.hpp>
#include <nt2/core/include/functions/disp.hpp>
#include <nt2/core/include/functions/display.hpp>
#include <nt2/core/include/functions/expand.hpp>
#include <nt2/core/include/functions/expand_to.hpp>
#include <nt2/core/include/functions/extent.hpp>
#include <nt2/core/include/functions/eye.hpp>
#include <nt2/core/include/functions/falses.hpp>
#include <nt2/core/include/functions/fill_pattern.hpp>
#include <nt2/core/include/functions/find.hpp>
#include <nt2/core/include/functions/findi.hpp>
#include <nt2/core/include/functions/findj.hpp>
#include <nt2/core/include/functions/finfj.hpp>
#include <nt2/core/include/functions/first_index.hpp>
#include <nt2/core/include/functions/firstnonsingleton.hpp>
#include <nt2/core/include/functions/firstoflength.hpp>
#include <nt2/core/include/functions/flipdim.hpp>
#include <nt2/core/include/functions/fliplr.hpp>
#include <nt2/core/include/functions/flipud.hpp>
#include <nt2/core/include/functions/fold.hpp>
#include <nt2/core/include/functions/freqspace.hpp>
#include <nt2/core/include/functions/freqspace1.hpp>
#include <nt2/core/include/functions/from_diag.hpp>
#include <nt2/core/include/functions/function.hpp>
#include <nt2/core/include/functions/function_size.hpp>
#include <nt2/core/include/functions/function_value_type.hpp>
#include <nt2/core/include/functions/generative.hpp>
#include <nt2/core/include/functions/global.hpp>
#include <nt2/core/include/functions/globalall.hpp>
#include <nt2/core/include/functions/globalany.hpp>
#include <nt2/core/include/functions/globalasum1.hpp>
#include <nt2/core/include/functions/globalasum2.hpp>
#include <nt2/core/include/functions/globalasump.hpp>
#include <nt2/core/include/functions/globalfind.hpp>
#include <nt2/core/include/functions/globalmax.hpp>
#include <nt2/core/include/functions/globalmean.hpp>
#include <nt2/core/include/functions/globalmeanad.hpp>
#include <nt2/core/include/functions/globalmedian.hpp>
#include <nt2/core/include/functions/globalmedianad.hpp>
#include <nt2/core/include/functions/globalmin.hpp>
#include <nt2/core/include/functions/globalnorm2.hpp>
#include <nt2/core/include/functions/globalnormp.hpp>
#include <nt2/core/include/functions/globalprod.hpp>
#include <nt2/core/include/functions/globalstdev.hpp>
#include <nt2/core/include/functions/globalsum.hpp>
#include <nt2/core/include/functions/globalvar.hpp>
#include <nt2/core/include/functions/havesamesize.hpp>
#include <nt2/core/include/functions/height.hpp>
#include <nt2/core/include/functions/horzcat.hpp>
#include <nt2/core/include/functions/idivide.hpp>
#include <nt2/core/include/functions/ifvectvert.hpp>
#include <nt2/core/include/functions/ind2ind.hpp>
#include <nt2/core/include/functions/ind2sub.hpp>
#include <nt2/core/include/functions/indices.hpp>
#include <nt2/core/include/functions/infs.hpp>
#include <nt2/core/include/functions/inner_fold.hpp>
#include <nt2/core/include/functions/inner_scan.hpp>
#include <nt2/core/include/functions/is_vectorizable_indexer.hpp>
#include <nt2/core/include/functions/iscolumn.hpp>
#include <nt2/core/include/functions/isdiagonal.hpp>
#include <nt2/core/include/functions/isempty.hpp>
#include <nt2/core/include/functions/isequal.hpp>
#include <nt2/core/include/functions/isequaln.hpp>
#include <nt2/core/include/functions/isexpandable_to.hpp>
#include <nt2/core/include/functions/isfloating.hpp>
#include <nt2/core/include/functions/ishermitian.hpp>
#include <nt2/core/include/functions/isinside.hpp>
#include <nt2/core/include/functions/isinteger.hpp>
#include <nt2/core/include/functions/ismatrix.hpp>
#include <nt2/core/include/functions/isreal.hpp>
#include <nt2/core/include/functions/isrow.hpp>
#include <nt2/core/include/functions/isscalar.hpp>
#include <nt2/core/include/functions/issorted.hpp>
#include <nt2/core/include/functions/issquare.hpp>
#include <nt2/core/include/functions/issymetric.hpp>
#include <nt2/core/include/functions/istriangular.hpp>
#include <nt2/core/include/functions/istril.hpp>
#include <nt2/core/include/functions/istriu.hpp>
#include <nt2/core/include/functions/isulpequal.hpp>
#include <nt2/core/include/functions/isvector.hpp>
#include <nt2/core/include/functions/isvectoralong.hpp>
#include <nt2/core/include/functions/last_index.hpp>
#include <nt2/core/include/functions/length.hpp>
#include <nt2/core/include/functions/line.hpp>
#include <nt2/core/include/functions/linear_interp.hpp>
#include <nt2/core/include/functions/linesstride.hpp>
#include <nt2/core/include/functions/linspace.hpp>
#include <nt2/core/include/functions/logspace.hpp>
#include <nt2/core/include/functions/make_size.hpp>
#include <nt2/core/include/functions/mean.hpp>
#include <nt2/core/include/functions/meanad.hpp>
#include <nt2/core/include/functions/median.hpp>
#include <nt2/core/include/functions/medianad.hpp>
#include <nt2/core/include/functions/nanasum2.hpp>
#include <nt2/core/include/functions/nanmean.hpp>
#include <nt2/core/include/functions/nans.hpp>
#include <nt2/core/include/functions/nansum.hpp>
#include <nt2/core/include/functions/nblines.hpp>
#include <nt2/core/include/functions/ndims.hpp>
#include <nt2/core/include/functions/norm2.hpp>
#include <nt2/core/include/functions/normp.hpp>
#include <nt2/core/include/functions/numel.hpp>
#include <nt2/core/include/functions/of_size.hpp>
#include <nt2/core/include/functions/ofsameheight.hpp>
#include <nt2/core/include/functions/ofsamewidth.hpp>
#include <nt2/core/include/functions/ones.hpp>
#include <nt2/core/include/functions/outer_fold.hpp>
#include <nt2/core/include/functions/outer_scan.hpp>
#include <nt2/core/include/functions/partial_fold.hpp>
#include <nt2/core/include/functions/pispace.hpp>
#include <nt2/core/include/functions/putalong.hpp>
#include <nt2/core/include/functions/rand.hpp>
#include <nt2/core/include/functions/randn.hpp>
#include <nt2/core/include/functions/reindex.hpp>
#include <nt2/core/include/functions/relative_index.hpp>
#include <nt2/core/include/functions/relative_size.hpp>
#include <nt2/core/include/functions/rephorz.hpp>
#include <nt2/core/include/functions/repmat.hpp>
#include <nt2/core/include/functions/repnum.hpp>
#include <nt2/core/include/functions/repvert.hpp>
#include <nt2/core/include/functions/reshape.hpp>
#include <nt2/core/include/functions/resize.hpp>
#include <nt2/core/include/functions/ric.hpp>
#include <nt2/core/include/functions/rif.hpp>
#include <nt2/core/include/functions/rows.hpp>
#include <nt2/core/include/functions/rowvect.hpp>
#include <nt2/core/include/functions/size.hpp>
#include <nt2/core/include/functions/squeeze.hpp>
#include <nt2/core/include/functions/stdev.hpp>
#include <nt2/core/include/functions/sub2ind.hpp>
#include <nt2/core/include/functions/sub2sub.hpp>
#include <nt2/core/include/functions/sx.hpp>
#include <nt2/core/include/functions/tie.hpp>
#include <nt2/core/include/functions/trans.hpp>
#include <nt2/core/include/functions/transform.hpp>
#include <nt2/core/include/functions/trapz.hpp>
#include <nt2/core/include/functions/tri1l.hpp>
#include <nt2/core/include/functions/tri1u.hpp>
#include <nt2/core/include/functions/tril.hpp>
#include <nt2/core/include/functions/triu.hpp>
#include <nt2/core/include/functions/trues.hpp>
#include <nt2/core/include/functions/tsxfun.hpp>
#include <nt2/core/include/functions/var.hpp>
#include <nt2/core/include/functions/vertcat.hpp>
#include <nt2/core/include/functions/width.hpp>
#include <nt2/core/include/functions/wmean.hpp>
#include <nt2/core/include/functions/zeros.hpp>

#endif
