#ifndef NT2_INCLUDE_FUNCTIONS_SCALAR_IS_SIMD_LOGICAL_HPP_INCLUDED
#define NT2_INCLUDE_FUNCTIONS_SCALAR_IS_SIMD_LOGICAL_HPP_INCLUDED

#include <nt2/toolbox/reduction/include/functions/scalar/is_simd_logical.hpp>

#endif
