#ifndef NT2_INCLUDE_FUNCTIONS_SCALAR_REPEAT_LOWER_HALF_HPP_INCLUDED
#define NT2_INCLUDE_FUNCTIONS_SCALAR_REPEAT_LOWER_HALF_HPP_INCLUDED

#include <nt2/toolbox/swar/include/functions/scalar/repeat_lower_half.hpp>

#endif
