__version__ = "0.1.26.post1.g678cbf1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@infinigit.infinidat.com:host/multipathtools.git'
__git_head_hash__ = '678cbf1bcd7f313e8efdc536588981bd7a0fffec'
__git_head_subject__ = 'HIP-1210'
__git_head_message__ = ''
__git_dirty_diff__ = ''