
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.1'
version_full = '91d85752b1e5ed9e7f9c141746f11358fd8bc135'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

