__version__ = "0.1.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '4f3972e923b951c7b54b732d5f5aecd948a1ad53'
__git_head_subject__ = 'refactoring and adding tests'
__git_head_message__ = ''
__git_dirty_diff__ = ''