# This file is autogenerated. Do not edit.
version_info = {
    "author": "Geert Jansen",
    "author_email": "geertj@gmail.com",
    "classifiers": [
        "Development Status :: 4 - Beta",
        "License :: OSI Approved :: MIT License",
        "Operating System :: POSIX",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: MacOS :: MacOS X",
        "Programming Language :: Python :: 2.6",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3.3",
        "Programming Language :: Python :: 3.4"
    ],
    "description": "Synchronous evented IO with pyuv and fibers",
    "license": "MIT",
    "name": "gruvi",
    "url": "https://github.com/geertj/gruvi",
    "version": "0.10.0"
}
