pages = [{
    "file": "google.html", 
    "num_links": 49,
    "limit_find": [{'seo': u'&sig=0_7kP1xQkn_3i8Oa3Nwzss U1QUqw%3D', 'text': u'Screen reader users, click here to turn off Google Instant.', 'href': u'https://www.google.com/setprefs?suggon=2&prev=https://www.google.com/&sig=0_7kP1xQkn_3i8Oa3Nwzss-U1QUqw%3D'}, {'seo': u'?tab=wX', 'text': u'+Eric', 'href': u'https://plus.google.com/u/0/?tab=wX'}, {'seo': u'?tab=wm', 'text': u'Gmail', 'href': u'https://mail.google.com/mail/?tab=wm'}, {'seo': u'imghp?hl=en&tab=wi&ei=gMR4U9ffF8iCqgbXr4LoDQ&ved=0CAQQqi4oAg', 'text': u'Images', 'href': u'https://www.google.com/imghp?hl=en&tab=wi&ei=gMR4U9ffF8iCqgbXr4LoDQ&ved=0CAQQqi4oAg'}, {'seo': u'', 'text': u'', 'href': u'http://www.google.com/intl/en/options/'}],
    "limit_reverse_find": [{'seo': u'answer.py?answer=186645&form=bb&hl=en', 'text': u'Learn more', 'href': u'https://www.google.com/support/websearch/bin/answer.py?answer=186645&form=bb&hl=en'}, {'seo': u'about.html?fg=1', 'text': u'About', 'href': u'https://www.google.com/intl/en/about.html?fg=1'}, {'seo': u'?fg=1', 'text': u'Business', 'href': u'https://www.google.com/services/?fg=1'}, {'seo': u'?fg=1', 'text': u'Advertising', 'href': u'https://www.google.com/intl/en/ads/?fg=1'}, {'seo': u'javascript:void(0)', 'text': u'  Send feedback ', 'href': u'javascript:void(0)'}],
    "limit_sort_text": [{'seo': u'', 'text': u'', 'href': u'http://www.google.com/intl/en/options/'}, {}, {'seo': u'me?tab=wX', 'text': u'me?tab=wX', 'href': u'https://plus.google.com/u/0/me?tab=wX'}, {'seo': u'webhp?tab=ww&ei=gMR4U9ffF8iCqgbXr4LoDQ&ved=0CBkQ1S4', 'text': u'webhp?tab=ww&ei=gMR4U9ffF8iCqgbXr4LoDQ&ved=0CBkQ1S4', 'href': u'https://www.google.com/webhp?tab=ww&ei=gMR4U9ffF8iCqgbXr4LoDQ&ved=0CBkQ1S4'}, {'seo': u'javascript:void(0)', 'text': u'  Send feedback ', 'href': u'javascript:void(0)'}],
    "limit_sort_href": [{'seo': u'&sig=0_7kP1xQkn_3i8Oa3Nwzss U1QUqw%3D', 'text': u'Screen reader users, click here to turn off Google Instant.', 'href': u'https://www.google.com/setprefs?suggon=2&prev=https://www.google.com/&sig=0_7kP1xQkn_3i8Oa3Nwzss-U1QUqw%3D'}, {'seo': u'?tab=wX', 'text': u'+Eric', 'href': u'https://plus.google.com/u/0/?tab=wX'}, {'seo': u'?tab=wm', 'text': u'Gmail', 'href': u'https://mail.google.com/mail/?tab=wm'}, {'seo': u'imghp?hl=en&tab=wi&ei=gMR4U9ffF8iCqgbXr4LoDQ&ved=0CAQQqi4oAg', 'text': u'Images', 'href': u'https://www.google.com/imghp?hl=en&tab=wi&ei=gMR4U9ffF8iCqgbXr4LoDQ&ved=0CAQQqi4oAg'}, {'seo': u'', 'text': u'', 'href': u'http://www.google.com/intl/en/options/'}]
}, {
    "file": "freep.html", 
    "num_links": 151,
    "limit_find": [{'seo': u'', 'text': u'click here', 'href': u'http://m.freep.com/'}, {'seo': u'%%=RedirectTo%28@fullurl1%29=%%', 'text': u'click here', 'href': u'http://www.freep.com/section/%%=RedirectTo%28@fullurl1%29=%%'}, {'seo': u'', 'text': u'', 'href': u'http://www.freep.com/'}, {'seo': u'facebook', 'text': u'facebook', 'href': u'http://www.freep.com/facebook'}, {'seo': u'twitter', 'text': u'twitter', 'href': u'http://www.freep.com/twitter'}],
    "limit_reverse_find": [{'seo': u'privacy#adchoices', 'text': u'Ad Choices', 'href': u'http://www.freep.com/section/privacy#adchoices'}, {'seo': u'privacy', 'text': u'Privacy Notice/Your California Privacy Rights', 'href': u'http://www.freep.com/section/privacy'}, {'seo': u'terms', 'text': u'Terms of Service', 'href': u'http://www.freep.com/terms'}, {'seo': u'subscription options&gps source=CPNLETSUB3', 'text': u'Subscribe to the Paper', 'href': u'http://www.freep.com/section/subscription-options&gps-source=CPNLETSUB3'}, {'seo': u'%%=RedirectTo%28@fullurl%29=%%', 'text': u'Unsubscribe to electronic mail', 'href': u'http://www.freep.com/section/%%=RedirectTo%28@fullurl%29=%%'}],
    "limit_sort_text": [{'seo': u'', 'text': u'', 'href': u'http://www.freep.com/'}, {'seo': u'facebook', 'text': u'facebook', 'href': u'http://www.freep.com/facebook'}, {'seo': u'twitter', 'text': u'twitter', 'href': u'http://www.freep.com/twitter'}, {'seo': u'rss', 'text': u'rss', 'href': u'http://www.freep.com/rss'}, {'seo': u'U.S. House candidate David Trott made millions in mortgage crisis', 'text': u'U.S. House candidate David Trott made millions in mortgage crisis', 'href': u'http://www.freep.com/article/20140518/NEWS06/305180087/U.S.-House-candidate-David-Trott-made-millions-in-mortgage-crisis'}],
    "limit_sort_href": [{'seo': u'', 'text': u'click here', 'href': u'http://m.freep.com/'}, {'seo': u'%%=RedirectTo%28@fullurl1%29=%%', 'text': u'click here', 'href': u'http://www.freep.com/section/%%=RedirectTo%28@fullurl1%29=%%'}, {'seo': u'', 'text': u'', 'href': u'http://www.freep.com/'}, {'seo': u'facebook', 'text': u'facebook', 'href': u'http://www.freep.com/facebook'}, {'seo': u'twitter', 'text': u'twitter', 'href': u'http://www.freep.com/twitter'}]
}]