# This file is generated by /Users/mb312/dev_trees/numpy-atlas-binaries/build/src/numpy_32/setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

atlas_threads_info={'libraries': ['lapack', 'ptf77blas', 'ptcblas', 'atlas'], 'language': 'f77', 'library_dirs': ['/Users/mb312/dev_trees/numpy-atlas-binaries/build/src/atlas_32/lib'], 'include_dirs': ['/Users/mb312/dev_trees/numpy-atlas-binaries/build/src/atlas_32/include'], 'define_macros': [('ATLAS_INFO', '"\\"3.10.1\\""')]}
mkl_info={}
atlas_blas_threads_info={'libraries': ['ptf77blas', 'ptcblas', 'atlas'], 'language': 'c', 'library_dirs': ['/Users/mb312/dev_trees/numpy-atlas-binaries/build/src/atlas_32/lib'], 'include_dirs': ['/Users/mb312/dev_trees/numpy-atlas-binaries/build/src/atlas_32/include'], 'define_macros': [('ATLAS_INFO', '"\\"3.10.1\\""')]}
blas_mkl_info={}
lapack_opt_info={'libraries': ['lapack', 'ptf77blas', 'ptcblas', 'atlas'], 'language': 'f77', 'library_dirs': ['/Users/mb312/dev_trees/numpy-atlas-binaries/build/src/atlas_32/lib'], 'include_dirs': ['/Users/mb312/dev_trees/numpy-atlas-binaries/build/src/atlas_32/include'], 'define_macros': [('ATLAS_INFO', '"\\"3.10.1\\""')]}
lapack_mkl_info={}
openblas_info={}
blas_opt_info={'libraries': ['ptf77blas', 'ptcblas', 'atlas'], 'language': 'c', 'library_dirs': ['/Users/mb312/dev_trees/numpy-atlas-binaries/build/src/atlas_32/lib'], 'include_dirs': ['/Users/mb312/dev_trees/numpy-atlas-binaries/build/src/atlas_32/include'], 'define_macros': [('ATLAS_INFO', '"\\"3.10.1\\""')]}

def get_info(name):
    g = globals()
    return g.get(name, g.get(name + "_info", {}))

def show():
    for name,info_dict in globals().items():
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print(name + ":")
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in info_dict.items():
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print("    %s = %s" % (k,v))
    