#ifndef NT2_TOOLBOX_REDUCTION_INCLUDE_FUNCTIONS_SCALAR_COMPARE_NOT_EQUAL_HPP_INCLUDED
#define NT2_TOOLBOX_REDUCTION_INCLUDE_FUNCTIONS_SCALAR_COMPARE_NOT_EQUAL_HPP_INCLUDED

#include <nt2/toolbox/reduction/functions/compare_not_equal.hpp>
#include <boost/simd/toolbox/reduction/functions/scalar/compare_not_equal.hpp>

#endif
