// Generated by CoffeeScript 1.7.1
(function() {
  var mainApp;

  mainApp = angular.module("MainApp");

  mainApp.controller('ProjectCtlr', [
    '$scope', '$location', '$route', '$q', '$filter', '$templateCache', 'Configuration', 'AppData', 'AppPref', 'Item', 'Itemizer', 'Minioner', 'Resulter', 'Jobber', 'ArgInfo', 'Runner', 'Wheeler', 'Commander', 'Pagerage', 'SaltApiSrvc', 'SaltApiEvtSrvc', 'SessionStore', '$filter', function($scope, $location, $route, $q, $filter, $templateCache, Configuration, AppData, AppPref, Item, Itemizer, Minioner, Resulter, Jobber, ArgInfo, Runner, Wheeler, Commander, Pagerage, SaltApiSrvc, SaltApiEvtSrvc, SessionStore) {
      $scope.errorMsg = "";
      return true;
    }
  ]);

}).call(this);
