#ifndef NT2_TOOLBOX_FUZZY_INCLUDE_FUNCTIONS_SCALAR_DEFINITELY_NOT_EQUAL_HPP_INCLUDED
#define NT2_TOOLBOX_FUZZY_INCLUDE_FUNCTIONS_SCALAR_DEFINITELY_NOT_EQUAL_HPP_INCLUDED

#include <nt2/toolbox/fuzzy/functions/definitely_not_equal.hpp>
#include <nt2/toolbox/fuzzy/functions/scalar/definitely_not_equal.hpp>

#endif
