#ifndef NT2_TOOLBOX_FUZZY_INCLUDE_FUNCTIONS_SCALAR_FUZZY_DEFINITELY_LESS_HPP_INCLUDED
#define NT2_TOOLBOX_FUZZY_INCLUDE_FUNCTIONS_SCALAR_FUZZY_DEFINITELY_LESS_HPP_INCLUDED

#include <nt2/toolbox/fuzzy/functions/fuzzy_definitely_less.hpp>
#include <nt2/toolbox/fuzzy/functions/scalar/fuzzy_definitely_less.hpp>

#endif
