__version__ = "0.1.10"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.10)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '4279610b8a1b329e4d592460d73d9884390b318b'
__git_head_subject__ = 'Finished release v0.1.10.'
__git_head_message__ = '* release/v0.1.10:\n  Check autostart status also in systemd (for centos7)\n  Fix the pid getter function (for centos7)'
__git_dirty_diff__ = ''