#ifndef BOOST_SIMD_TOOLBOX_BOOLEAN_INCLUDE_FUNCTIONS_SCALAR_IF_ALLBITS_ELSE_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_BOOLEAN_INCLUDE_FUNCTIONS_SCALAR_IF_ALLBITS_ELSE_HPP_INCLUDED

#include <boost/simd/toolbox/boolean/functions/if_allbits_else.hpp>
#include <boost/simd/toolbox/boolean/functions/scalar/if_allbits_else.hpp>

#endif
