#ifndef NT2_TOOLBOX_BOOST_MATH_INCLUDE_FUNCTIONS_GAMMA_P_DERIVATIVE_HPP_INCLUDED
#define NT2_TOOLBOX_BOOST_MATH_INCLUDE_FUNCTIONS_GAMMA_P_DERIVATIVE_HPP_INCLUDED

#include <nt2/toolbox/boost_math/functions/gamma_p_derivative.hpp>
#include <nt2/toolbox/boost_math/functions/scalar/gamma_p_derivative.hpp>

#endif
