#ifndef NT2_TOOLBOX_BOOST_MATH_INCLUDE_FUNCTIONS_SPHERICAL_HARMONIC_I_HPP_INCLUDED
#define NT2_TOOLBOX_BOOST_MATH_INCLUDE_FUNCTIONS_SPHERICAL_HARMONIC_I_HPP_INCLUDED

#include <nt2/toolbox/boost_math/functions/spherical_harmonic_i.hpp>
#include <nt2/toolbox/boost_math/functions/scalar/spherical_harmonic_i.hpp>

#endif
