
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.12.7'
version_full = '1d7b58fe0e36fc7a7b4ccbfa589e9e94d038886b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

