__version__ = "0.6.11"
__git_commiter_name__ = "Tomer Galun"
__git_commiter_email__ = "tomerg@infinidat.com"
__git_branch__ = '(detached from v0.6.11)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'f713d5faedd28702759f71675f22f90ecd090905'
__git_head_subject__ = 'HOSTDEV-1717 Replace platform.dist with linux_distribution'
__git_head_message__ = ''
__git_dirty_diff__ = ''