__version__ = "0.1.3"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a7e970641dd5161d62c8754b68eb4cddf0d4eb87'
__git_head_subject__ = 'HOSTDEV-1703 inner directory now based on the collected timestamp instead of now()'
__git_head_message__ = ''
__git_dirty_diff__ = ''