__version__ = "0.2.14"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.14)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '2641e3337681c9c250c40db0bee99db102e7d485'
__git_head_subject__ = 'Finished release v0.2.14.'
__git_head_message__ = '* release/v0.2.14:\n  STORAGEMODEL-275 fixing SyntaxError in previous commit\n  STORAGEMODEL-275 fixing ImportError in previous commit\n  STORAGEMODEL-275 increasing the timeout used in communicated with multipathd to 120 seconds'
__git_dirty_diff__ = ''